### PR TITLE
Check if python module exists to fix #3613

### LINKED ISSUE #3613: Usability: Direct scan from Polars requires that Pandas is also installed
### Kùzu version

0.4.3.dev27

### What happened?

Currently, if we want to scan from a Polars DataFrame, it seems to require that Pandas is also installed (see below). The ideal use case for this feature would be that users who want to use Polars do not want to rely on Pandas.

### Are there known steps to reproduce?

Create a file named `test.csv` with the following content:

```
id,text
1,"Some sample text."
```
Install only Polars and PyArrow (not Pandas) to mimic the use case where a user doesn't want a Pandas dependency.
```
pip install polars pyarrow
```

Running this code will produce the following error.
```py
import shutil
import kuzu
import polars as pl

shutil.rmtree("./test", ignore_errors=True)
db = kuzu.Database("./test")
conn = kuzu.Connection(db)

df = pl.read_csv("test.csv")
print(df.head())


res = conn.execute("LOAD FROM df (header=true) RETURN *").get_as_pl()
print(res)
```
Error:
```
Traceback (most recent call last):
  File "/Users/prrao/code/kuzu-debug/tt.py", line 13, in <module>
    res = conn.execute("LOAD FROM df (header=true) RETURN *").get_as_pl()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prrao/code/kuzu-debug/.venv/lib/python3.11/site-packages/kuzu/connection.py", line 130, in execute
    _query_result = self._connection.query(query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ModuleNotFoundError: No module named 'pandas'
```

If I run `pip install pandas` and rerun the above code, the direct scan works as intended.

### PR DESCRIPTION
**Pull request by mxwli**
Fixes #3613

assumes that if the pandas/polars module does not exist, then the object is not a pandas/polars Dataframe instance.

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: tools/python_api/src_cpp/include/cached_import/py_cached_modules.h [hunk 1]
```diff
@@ -24,6 +24,23 @@ class DecimalCachedItem : public PythonCachedItem {
     PythonCachedItem Decimal;
 };
 
+class ImportLibCachedItem : public PythonCachedItem {
+
```
Comment (acquamarin) [inline tools/python_api/src_cpp/include/cached_import/py_cached_modules.h:28]: Remove space

File: tools/python_api/src_cpp/include/cached_import/py_cached_modules.h [hunk 2]
```diff
@@ -24,6 +24,23 @@ class DecimalCachedItem : public PythonCachedItem {
...
+    class UtilCachedItem : public PythonCachedItem {
+
+    public:
+        explicit UtilCachedItem(PythonCachedItem* parent)
+            : PythonCachedItem("util", parent), find_spec("find_spec", this) {}
```
Comment (acquamarin) [inline tools/python_api/src_cpp/include/cached_import/py_cached_modules.h:33]: We prefer to use bracket initilization pattern. 
PythonCachedItem{"util", parent}
find_spec{"find_spec", this}

**Review by acquamarin — APPROVED** [review]
