### PR TITLE
Fix #2704

### LINKED ISSUE #2704: Give error message when wrong option is used in the copy statement
Some copy options are only supported in csv (e.g. header=true). If the user provides those options while loading a parquet file, the binder should error.
Example:
`COPY tableOfTypes FROM "s3://kuzu-dataset-us/types_50k_*.parquet" (header=true)`

### PR DESCRIPTION
**Pull request by manh9203**
This PR resolved #2704.

### CODE REVIEW

File: src/binder/bind/bind_import_database.cpp [hunk 1]
```diff
@@ -55,12 +55,19 @@ std::unique_ptr<BoundStatement> Binder::bindImportDatabaseClause(const Statement
...
-        auto csvQuery = stringFormat("COPY {} FROM \"{}\" {};", copyFromStatement->getTableName(),
-            copyFilePath, csvConfig.option.toCypher());
-        finalQueryStatements += csvQuery;
+        std::string query;
+        if (fileType == FileType::CSV) {
+            auto csvConfig = CSVReaderConfig::construct(
+                bindParsingOptions(copyFromStatement->getParsingOptionsRef()));
+            query = stringFormat("COPY {} FROM \"{}\" {};", copyFromStatement->getTableName(),
+                copyFilePath, csvConfig.option.toCypher());
+        } else {
```
Comment (andyfengHKU) [inline src/binder/bind/bind_import_database.cpp:66]: Why is the else statement needed? If we export in non-csv format then their shouldn't be options in the first place.

File: src/binder/bind/bind_file_scan.cpp [hunk 2]
```diff
@@ -75,6 +75,9 @@ std::unique_ptr<BoundBaseScanSource> Binder::bindScanSource(BaseScanSource* sour
         auto filePaths = bindFilePaths(fileSource->filePaths);
         // Bind file type.
         auto fileType = bindFileType(filePaths);
+        if (fileType != FileType::CSV && options.size() != 0) {
```
Comment (andyfengHKU) [inline src/binder/bind/bind_file_scan.cpp:78]: I doubt this is the best place to perform the check because it's not scalable if we want to add another file type in the future.

A better design it to always parse options and save it in `ScanTableFuncBindInput`.  Then each scan function should have its own bind option logic. For csv scan, it will construct a csv option. For parquet it should validate no option. And I'm sure you also need to do it for npy.

**Review by andyfengHKU — CHANGES_REQUESTED** [review]

File: src/processor/operator/persistent/reader/npy/npy_reader.cpp [hunk 3]
```diff
@@ -296,6 +297,9 @@ static void bindColumns(const common::ReaderConfig& readerConfig,
 static std::unique_ptr<function::TableFuncBindData> bindFunc(main::ClientContext* /*context*/,
     function::TableFuncBindInput* input) {
     auto scanInput = reinterpret_cast<function::ScanTableFuncBindInput*>(input);
+    if (!scanInput->config.options.empty()) {
+        throw BinderException{"Copy from Npy cannot have options."};
```
Comment (andyfengHKU) [inline src/processor/operator/persistent/reader/npy/npy_reader.cpp:301]: Write a test to cover this.

File: test/test_files/copy/copy_node_parquet.test [hunk 4]
```diff
@@ -53,3 +53,9 @@
 -STATEMENT MATCH (row:tableOfTypes) WHERE 0 <= row.doubleColumn AND row.doubleColumn <= 10 AND 0 <= row.int64Column AND row.int64Column <= 10 RETURN count(*);
 ---- 1
 546
+
+-CASE CopyWithOptionsErrorTest
```
Comment (andyfengHKU) [inline test/test_files/copy/copy_node_parquet.test:57]: I guess to don't need to start a new case maybe?

**Review by andyfengHKU — APPROVED** [review]
