### PR TITLE
Fix top-k flat/unflat bug

### LINKED ISSUE #2648: ORDER BY returns incorrect number of tuples in result
I'm not sure if this is a bug, but the behaviour is definitely unexpected.

Python workflow is used to produce the issue.

```bash
pip install kuzu pandas
```

Kùzu version: 0.1.0

## Scenario

Consider the following two input CSV files that represent relationships between people.

`person_nodes.csv`
```
id,name,gender,age
1,Kenneth Scott,male,29
2,Stephanie Scott,female,26
3,Laura Williams,female,39
```

`person_edges.csv`
```
from,to,relationship
1,2,family_member
1,3,business_associate
2,3,business_associate
```

#### `build_graph.py`

```python
import os
import shutil

import kuzu


def create_person_node_table(conn: kuzu.Connection) -> None:
    conn.execute(
        """
        CREATE NODE TABLE Person(
            id INT64,
            name STRING,
            gender STRING,
            age INT64,
            PRIMARY KEY(id)
        )
    """
    )


def create_person_edge_table(conn: kuzu.Connection) -> None:
    conn.execute(
        """
        CREATE REL TABLE Knows(
            FROM Person to Person,
            relationship STRING
        )
    """
    )

DB_NAME = "test"
if os.path.exists(DB_NAME):
    shutil.rmtree(DB_NAME)

db = kuzu.Database(DB_NAME)
conn = kuzu.Connection(db)

create_person_node_table(conn)
create_person_edge_table(conn)

conn.execute("COPY Person FROM 'person_nodes.csv' (header=true);")
conn.execute("COPY Knows FROM 'person_edges.csv' (header=true);")
```

#### `query.py`

```python
import kuzu

query = """
    MATCH (a:Person)-[r:Knows]->(b:Person)
    RETURN a.name, r.relationship, b.name
    LIMIT 10;
"""

DB_NAME = "test"
db = kuzu.Database(DB_NAME)
conn = kuzu.Connection(db)

print(f"Query: {query}")
response = conn.execute(query)
num_tuples = response.get_num_tuples()
result = response.get_as_df()
print(f"Result:\n{result}")
print(f"\nObtained {num_tuples} tuples in result")
```

## Expected result

When we run this query, we obtain 3 tuples in the result as expected. 
```sql
    MATCH (a:Person)-[r:Knows]->(b:Person)
    RETURN a.name, r.relationship, b.name
    LIMIT 10;
```

```
Result:
            a.name      r.relationship           b.name
0    Kenneth Scott       family_member  Stephanie Scott
1    Kenneth Scott  business_associate   Laura Williams
2  Stephanie Scott  business_associate   Laura Williams

Obtained 3 tuples in result
```

## Unexpected result

However, when we run this query with an `ORDER BY` clause, we obtain 5 tuples, which is incorrect.

```sql
    MATCH (a:Person)-[r:Knows]->(b:Person)
    RETURN a.name, r.relationship, b.name
    ORDER BY a.name
    LIMIT 10;
```

```
Result:
            a.name      r.relationship           b.name
0                        family_member  Stephanie Scott
1                   business_associate   Laura Williams
2    Kenneth Scott       family_member  Stephanie Scott
3    Kenneth Scott  business_associate   Laura Williams
4  Stephanie Scott  business_associate   Laura Williams

Obtained 5 tuples in result
```

What could be going wrong? Is the Cypher query projection not being done as expected?

### PR DESCRIPTION
**Pull request by acquamarin**
close #2648 
This PR solves a flat/unflat bug in top-k.
## Bug:
Assume we are planning to read two columns(a, b) from a factorized table to two unflat vectors ,  where `a` is a flat column and `b` is an unflat column. We don't duplicate the values in column `a` as the number of `b` values when reading from the factorized table.
E.g. a: 2, b: [1,4,5]
The result vector a, b should look like:
a: [2,2,2] (2 is duplicated 3 times in a)
b: [1,4,5]
## Solution:
Instead of blindly creating unflat vectors when reading from flat columns, we now create flat vectors.

### CODE REVIEW

File: src/processor/operator/order_by/sort_state.cpp [hunk 1]
```diff
@@ -107,53 +108,85 @@ PayloadScanner::PayloadScanner(MergedKeyBlocks* keyBlockToScan,
 }
 
 uint64_t PayloadScanner::scan(std::vector<common::ValueVector*> vectorsToRead) {
-    if (nextTupleIdxToReadInMergedKeyBlock >= endTuplesIdxToReadInMergedKeyBlock) {
+    if (limitNumber <= 0 ||
```
Comment (andyfengHKU) [inline src/processor/operator/order_by/sort_state.cpp:111]: Do we have a test where limitNumber < 0 ? I thought binder will throw in this case.

File: src/processor/operator/order_by/sort_state.cpp [hunk 2]
```diff
@@ -107,53 +108,85 @@ PayloadScanner::PayloadScanner(MergedKeyBlocks* keyBlockToScan,
...
+        // lookup function doesn't perform a check on whether it holds all the tuples in
+        // tuplesToRead. We should optimize this lookup function in the orderByScan
+        // optimization PR.
+        payloadTables[0]->lookup(vectorsToRead, colsToScan, tuplesToRead.get(), 0, numTuplesToRead);
+        nextTupleIdxToReadInMergedKeyBlock += numTuplesToRead;
+        return numTuplesRead;
+    }
+}
+
+bool PayloadScanner::scanSingleTuple(std::vector<common::ValueVector*> vectorsToRead) const {
```
Comment (andyfengHKU) [inline src/processor/operator/order_by/sort_state.cpp:157]: This is a pure compile time check. Open an issue for me to fix.

**Review by andyfengHKU — APPROVED** [review]

File: src/processor/operator/order_by/sort_state.cpp (hunk 1 above)
Comment (acquamarin) [reply src/processor/operator/order_by/sort_state.cpp:111]: This variable is used as a counter, so i will decrease the counter after each scan.

File: src/processor/operator/order_by/sort_state.cpp (hunk 2 above)
Comment (acquamarin) [reply src/processor/operator/order_by/sort_state.cpp:157]: #2652
