### PR TITLE
Pandas UUID

### LINKED ISSUE #3587: Bug: KU_UNREACHABLE for UUID values when copying from a loaded DataFrame
### Kùzu version

v0.4.2

## Summary

When copying to a table from a loaded DataFrame containing UUID values, Kùzu raises a `KU_UNREACHABLE` error and no data is copied.

## My Story

I'm building a graph consisting of potentially multi-line blocks of text identified by UUID, and exploring ways to do this without the reformatting hassle of CSV or the performance hit of of CREATE statements (though performance is improved by wrapping the create statements in a transaction).

The support for copying from a loaded DataFrame seems promising, but Kùzu raises an error when UUID values are loaded from a DataFrame.

Output using the code in reproducing section code sample:

```
Traceback (most recent call last):
  File "/Users/random/dev/kuzu-uuid-bug/main.py", line 13, in <module>
    conn.execute("COPY Block FROM (LOAD FROM df RETURN *)")
  File "/Users/random/dev/kuzu-uuid-bug/.venv/lib/python3.11/site-packages/kuzu/connection.py", line 131, in execute
    _query_result = self._connection.query(query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Assertion failed in file "/private/var/folders/7v/l3_p0vq96qn_ck27n1cq5ql80000gn/T/cibw-sdist-ajrk0lr5/sdist/kuzu-source/tools/python_api/src_cpp/py_conversion.cpp" on line 33: KU_UNREACHABLE
```

I have been unable to find a workaround on my own. The database recognizes the value is a string when it should be a UUID if I attempt to use `uuid4().hex`, and does not copy the data.

I am new to Kùzu and Cypher, so if there's a correct path or workaround I'm missing, please let me know!

## System

- Operating System: macOS Sonoma 14.5
- Python: 3.11.4
- Kuzu: v0.4.2
- PyArrow: 16.1.0
- Pandas: 2.2.2

### Are there known steps to reproduce?

Here's a minimal case to reproduce on my system:

```python
import uuid

import kuzu
import pandas as pd


db_name = "db"
db = kuzu.Database(db_name)
conn = kuzu.Connection(db)
conn.execute("CREATE NODE TABLE Block ( uuid uuid, primary key (uuid));")
df = pd.DataFrame([{"uuid": uuid.uuid4()}])
conn.execute("COPY Block FROM (LOAD FROM df RETURN *)")
```

### PR DESCRIPTION
**Pull request by mxwli**
# Description

Adds scanning from UUID columns from pandas DataFrames; adds tests as well

Fixes #3587 

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: tools/python_api/src_cpp/py_conversion.cpp [hunk 1]
```diff
@@ -105,6 +111,12 @@ void transformPythonValue(common::ValueVector* outputVector, uint64_t pos, py::h
     case PythonObjectType::List: {
         transformListValue(outputVector, pos, ele);
     } break;
+    case PythonObjectType::UUID: {
+        outputVector->setNull(pos, false /* isNull */);
+        int128_t result;
+        UUID::fromString(ele.attr("hex").cast<std::string>(), result);
```
Comment (mxwli) [inline tools/python_api/src_cpp/py_conversion.cpp:117]: Should I use a faster method?

**Review by andyfengHKU — APPROVED** [review]

File: mm-256KB
Comment (andyfengHKU) [inline mm-256KB:1]: Remove this. And squash before merging.
