### PR TITLE
Fix distinct aggregation on recursive rel

### LINKED ISSUE #3749: Bug: DISTINCT on recursive relationship leads to an Assertion failure
### Kùzu version

v0.4.2

### What operating system are you using?

MacOS

### What happened?

I am running this query and getting an assertion error:
```
MATCH (a:Person)-[t*1..5]-(b:Person) RETURN DISTINCT *;
```
The following assertion fails:
`Error: Assertion failed in file "/tmp/kuzu-20240514-6573-3phczn/kuzu-0.4.2/src/function/vector_hash_functions.cpp" on line 124: KU_UNREACHABLE`

Removing the DISTINCT solves the issue.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by acquamarin**
# Description
This PR fixes hash opeartion on recursive rel.

Fixes #3749

### CODE REVIEW

File: src/common/types/types.cpp [hunk 1]
```diff
@@ -1120,7 +1120,7 @@ std::vector<LogicalTypeID> LogicalTypeUtils::getAllValidLogicTypeIDs() {
         LogicalTypeID::TIMESTAMP_TZ, LogicalTypeID::INTERVAL, LogicalTypeID::LIST,
         LogicalTypeID::ARRAY, LogicalTypeID::MAP, LogicalTypeID::FLOAT, LogicalTypeID::SERIAL,
         LogicalTypeID::NODE, LogicalTypeID::REL, LogicalTypeID::STRUCT, LogicalTypeID::UNION,
-        LogicalTypeID::RDF_VARIANT};
+        LogicalTypeID::RDF_VARIANT, LogicalTypeID::RECURSIVE_REL};
```
Comment (andyfengHKU) [inline src/common/types/types.cpp:1123]: put RECURSIVE_REL after NODE & REL

File: test/test_files/tinysnb/agg/distinct_agg.test [hunk 2]
```diff
@@ -117,3 +117,7 @@ Bob|Dan
 2000-01-01|Dan
 2021-06-30|Carol
 2021-06-30|Dan
+-LOG DistinctRecursiveRel
+-STATEMENT MATCH (a:person)-[t:knows*1..3]-(b:person) RETURN count(DISTINCT t);
```
Comment (andyfengHKU) [inline test/test_files/tinysnb/agg/distinct_agg.test:121]: if we do count(t), do we also get 1036? Not sure if we have duplicated `t` in this case.

**Review by andyfengHKU — APPROVED** [review]
