### PR TITLE
reader/csv: use exception-safe locks

### LINKED ISSUE #2253: copying from CSV file with (PARALLEL=false) may get stuck if error is encountered
### How to reproduce:
a.csv:
```
a
```
schema.cypher:
```
CREATE NODE TABLE t (id INT64, PRIMARY KEY (id));
```
copy.cypher:
```
COPY t FROM "a.csv";
```
copy2.cypher:
```
COPY t FROM "a.csv" (PARALLEL=false);
```
Executing `cat schema.cypher copy.cypher | path/to/kuzu_shell ./t` creates the table and throws a conversion exception, as expected, but
Executing `cat schema.cypher copy2.cypher | path/to/kuzu_shell ./t2` creates the table and then gets stuck.

### PR DESCRIPTION
**Pull request by Riolku**
Closes #2253. Exceptions in the CSV parsing could cause a task to never wake up from sleeping on a lock.

### CODE REVIEW

File: src/include/processor/operator/persistent/reader.h [hunk 1]
```diff
@@ -57,15 +57,11 @@ class Reader : public PhysicalOperator {
     void readNextDataChunk();
 
     template<ReaderSharedState::ReadMode READ_MODE>
-    inline void lockForSerial() {
+    [[nodiscard]] inline auto lockForSerial() {
```
Comment (acquamarin) [inline src/include/processor/operator/persistent/reader.h:60]: We always explicitly write the return type instead of auto in function declaration/implementation.
I am a little bit confused about the return type:
 std::lock_guard and nullptr has different type, how can we return two different types in the same function?
BTW: We never use nodiscard in the code base,  should we use it from now on?

File: test/test_files/csv/errors.test [hunk 2]
```diff
@@ -31,3 +31,9 @@ Copy exception: Error in file ${KUZU_ROOT_DIRECTORY}/dataset/csv-error-tests/too
 -STATEMENT LOAD FROM "${KUZU_ROOT_DIRECTORY}/dataset/csv-error-tests/union-no-conversion.csv" (HEADER=TRUE) RETURN *
 ---- error
 Conversion exception: Could not convert to union type UNION(u:UINT8, s:INT8): a.
+
+# Test that errors in serial mode don't hang the database.
+# File is large so the window for the race is large enough.
+-STATEMENT LOAD FROM "${KUZU_ROOT_DIRECTORY}/dataset/csv-error-tests/large-conversion-failure.csv" (HEADER=TRUE, PARALLEL=FALSE) RETURN *
```
Comment (acquamarin) [inline test/test_files/csv/errors.test:37]: If you don't write header=true, you can remove the title in the csv file.

**Review by acquamarin — APPROVED** [review]

File: src/include/processor/operator/persistent/reader.h (hunk 1 above)
Comment (Riolku) [reply src/include/processor/operator/persistent/reader.h:60]: `auto` is used to enable this confusing behaviour. We have no lock to hold if `READ_MODE` is parallel, so we return a dummy object.

Since this is a templated function, it can have *two return values depending on READ_MODE*.

Another way to write this would be using template specialization, which might be easier to understand. Thoughts?

On the topic of `[[nodiscard]]`, it's a particularly nice convention here because it makes it obvious that `lockForSerial()` shouldn't be ignored (since it's a lock guard).

Should we use it everywhere? Maybe. Continuing to add things to bulletproof our codebase is a good idea, and this is one of them. There's even a `clang-tidy` [check](https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-nodiscard.html) for using `[[nodiscard]]` on all `const` functions (since they have no way of modifying the object, and discarding the result is likely an error).

Comment (acquamarin) [reply src/include/processor/operator/persistent/reader.h:60]: I would prefere using template specialization, this function is too confusing.

Comment (Riolku) [reply src/include/processor/operator/persistent/reader.h:60]: Seems template specialization won't work since the signatures have to match. I'll use a `unique_ptr`.

Comment (Riolku) [reply src/include/processor/operator/persistent/reader.h]: Updated to use `std::optional`
