### PR TITLE
Csv sniffing

### LINKED ISSUE #2434: Auto-renaming when two columns in csv file share the same name.
1.csv:
```
a,a
1,3
```
Query:
```
create node table person (id int64, id1 int64, primary key(id));
load from '1.csv' (header=true)
```
Binder needs to rename the second column during conflict.

### LINKED ISSUE #3931: CSV LIST_BEGIN and LIST_END options do not exist
### Description

In our [csv loading documentation](https://docs.kuzudb.com/import/csv/), we specify for the `list_begin` and `list_end` parameters to denote the beginning and ending of lists. These parameters are not real; the usage of them yields `Error: Binder exception: Unrecognized csv parsing option: LIST_BEGIN.`

### Link

_No response_

### PR DESCRIPTION
**Pull request by mxwli**
Fixes #2434
Fixes #3931
Implements CSV sniffing
Fixes DECIMAL comparison, which was previously held together by hopes, dreams, and gorilla glue

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/common/types/types.cpp [hunk 1]
```diff
@@ -1748,5 +1801,68 @@ bool LogicalTypeUtils::tryGetMaxLogicalType(const std::vector<LogicalType>& type
     return true;
 }
 
+LogicalType LogicalTypeUtils::combineTypes(const common::LogicalType& lft,
```
Comment (andyfengHKU) [inline src/common/types/types.cpp:1804]: If u are introducing this, we need to document under what case we should use getMaxLogicalType and what case we should use combineTypes. How are they different from each other.

File: test/test_files/copy/copy_to_csv.test [hunk 2]
```diff
@@ -9,7 +9,7 @@
 -STATEMENT load from "${DATABASE_PATH}/tinysnb_person.csv"(header=true) return *
 ---- 8
 [0:0]|0|Alice|1|True|False|35|5.000000|1900-01-01|2011-08-20 11:25:30|3 years 2 days 13:02:00|[10,5]|[Aida]|[[10,8],[6,7,8]]|[96,54,86,92]|1.731000|a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
-[0:1]|2|Bob|2|True|False|30|5.100000|1900-01-01|2008-11-03 15:25:30.000526|10 years 5 months 13:00:00.000024|[12,8]|[Bobby]|[[8,9],[9,10]]|[98,42,93,88]|0.990000|a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12
+[0:1]|2|Bob|2|True|False|30|5.100000|1900-01-01|2008-11-03 15:25:30.000526|10 years 5 months 13:00:00.000024|[12,8]|[Bobby]|[[8,9],[9,10]]|[98,42,93,88]|.990000|a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12
```
Comment (andyfengHKU) [inline test/test_files/copy/copy_to_csv.test:12]: Is this 0.990000 -> .990000 change expected?

File: src/processor/operator/persistent/reader/reader_bind_utils.cpp [hunk 3]
```diff
@@ -23,10 +24,13 @@ void ReaderBindUtils::validateColumnTypes(const std::vector<std::string>& column
     const std::vector<common::LogicalType>& detectedColumnTypes) {
     KU_ASSERT(expectedColumnTypes.size() == detectedColumnTypes.size());
     for (auto i = 0u; i < expectedColumnTypes.size(); ++i) {
-        if (expectedColumnTypes[i] != detectedColumnTypes[i]) {
-            throw common::BinderException(common::stringFormat(
-                "Column `{}` type mismatch. Expected {} but got {}.", columnNames[i],
-                expectedColumnTypes[i].toString(), detectedColumnTypes[i].toString()));
+        if (!function::CastFunction::hasImplicitCast(expectedColumnTypes[i],
```
Comment (andyfengHKU) [inline src/processor/operator/persistent/reader/reader_bind_utils.cpp:27]: I doubt this is expected. When there are multiple parquet files, we do expect their column to have the same data type because the current implementation will first scan from all parquet files and then cast.

To support what u have in mind, we need to cast inside each parquet.

File: src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp [hunk 4]
```diff
@@ -17,21 +16,25 @@ SerialCSVReader::SerialCSVReader(const std::string& filePath, CSVOption option,
...
+        // ideally "col_{N}" shouldn't exist, but if it already exists M times (due to user
+        // declaration), rename to "col_{N}" + "_{M}" repeat until no match exists
+        while (names.contains(i.first)) {
+            names[i.first]++;
+            i.first += "_" + std::to_string(names[i.first]);
         }
-        return columns;
+        names[i.first];
+        // purge null types
+        i.second = LogicalTypeUtils::purgeAny(i.second, LogicalType::STRING());
```
Comment (andyfengHKU) [inline src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp:35]: Under what case do we need purge? Sounds like u should default it to STRING at the time of sniffing

File: src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp [hunk 5]
```diff
@@ -17,21 +16,25 @@ SerialCSVReader::SerialCSVReader(const std::string& filePath, CSVOption option,
...
     }
+    return std::move(driver.columns);
```
Comment (andyfengHKU) [inline src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp:37]: I'm pretty sure this std::move is unnecessary. U don't get any performant benefit from this move, in fact it may even mislead compiler in some cases and miss potential optimization.

File: src/processor/operator/persistent/reader/csv/driver.cpp [hunk 6]
```diff
@@ -85,51 +85,55 @@ BaseCSVReader* SerialParsingDriver::getReader() {
...
-    return true;
-}
-
-bool SniffCSVColumnCountDriver::done(uint64_t) const {
-    return !emptyRow;
+    return (csvOptions.hasHeader ? 1 : 0) + csvOptions.sampleSize <= (int64_t)rowNum;
 }
 
-void SniffCSVColumnCountDriver::addValue(uint64_t, common::column_id_t columnIdx,
+void SniffCSVNameAndTypeDriver::addValue(uint64_t rowNum, common::column_id_t columnIdx,
```
Comment (andyfengHKU) [inline src/processor/operator/persistent/reader/csv/driver.cpp:95]: So we don't seem to be able to sniff delimiter, line breaker, etc.

File: src/binder/bind_expression/bind_comparison_expression.cpp [hunk 7]
```diff
@@ -52,6 +52,9 @@ std::shared_ptr<Expression> ExpressionBinder::bindComparisonExpression(
             childrenAfterCast.push_back(children[i]);
         }
     }
+    if (function->bindFunc) { // Resolve exec and select function if necessary
```
Comment (andyfengHKU) [inline src/binder/bind_expression/bind_comparison_expression.cpp:55]: Be specific that this is for decimal.

File: src/function/cast_string_non_nested_functions.cpp [hunk 8]
```diff
@@ -83,5 +88,94 @@ bool TryCastStringToTimestamp::tryCast<timestamp_sec_t>(const char* input, uint6
     return true;
 }
 
+static bool isDate(const std::string& str) {
+    return RE2::FullMatch(str, "\\d{4}/\\d{1,2}/\\d{1,2}") ||
```
Comment (acquamarin) [inline src/function/cast_string_non_nested_functions.cpp:92]: I think the first match is trying to match date with style: 
2023/8/7, 1999/12/31.
I don't think our csv reader support such format.

File: src/function/cast_string_non_nested_functions.cpp [hunk 9]
```diff
@@ -83,5 +88,94 @@ bool TryCastStringToTimestamp::tryCast<timestamp_sec_t>(const char* input, uint6
...
+           RE2::FullMatch(str, "\\d{4}-\\d{1,2}-\\d{1,2}") ||
+           RE2::FullMatch(str, "\\d{4} \\d{1,2} \\d{1,2}") ||
```
Comment (acquamarin) [inline src/function/cast_string_non_nested_functions.cpp:94]: We only support the second way of representing date.

File: src/function/cast_string_non_nested_functions.cpp [hunk 10]
```diff
@@ -83,5 +88,94 @@ bool TryCastStringToTimestamp::tryCast<timestamp_sec_t>(const char* input, uint6
...
+        if (cpy.size() <= DECIMAL_PRECISION_LIMIT) {
+            auto decimalPoint = cpy.find('.');
+            KU_ASSERT(decimalPoint != std::string::npos);
+            return LogicalType::DECIMAL(cpy.size() - 1, cpy.size() - decimalPoint - 1);
+        } else {
+            return LogicalType::DOUBLE();
+        }
+    }
+    // date
+    if (isDate(cpy)) {
```
Comment (acquamarin) [inline src/function/cast_string_non_nested_functions.cpp:142]: What about uuid and interval?

File: src/include/common/constants.h [hunk 11]
```diff
@@ -144,8 +144,9 @@ struct CopyConstants {
     static constexpr const char* ROW_IDX_COLUMN_NAME = "ROW_IDX";
     static constexpr uint64_t PANDAS_PARTITION_COUNT = 50 * DEFAULT_VECTOR_CAPACITY;
 
-    static constexpr const char* INT_CSV_PARSING_OPTIONS[] = {"SKIP"};
+    static constexpr const char* INT_CSV_PARSING_OPTIONS[] = {"SKIP", "SAMPLE_SIZE"};
     static constexpr uint64_t DEFAULT_CSV_SKIP_NUM = 0;
+    static constexpr int64_t DEFAULT_CSV_TYPE_DEDUCTION_SAMPLE_SIZE = -1;
```
Comment (acquamarin) [inline src/include/common/constants.h:149]: I think the default value should be 0 instead of -1

File: src/include/common/copier_config/csv_reader_config.h [hunk 12]
```diff
@@ -14,13 +14,15 @@ struct CSVOption {
     char quoteChar;
     bool hasHeader;
     uint64_t skipNum;
+    int64_t sampleSize;
```
Comment (acquamarin) [inline src/include/common/copier_config/csv_reader_config.h:17]: Use uint64_t, sample size should never be a negative int

File: src/include/common/constants.h (hunk 11 above)
Comment (mxwli) [reply src/include/common/constants.h:149]: Negative value means to scan the whole table for sniffing. This is inefficient, as suggested by previous experiences with the parameter, so I'll be setting it to 2048. Hopefully this doesn't break any tests.

File: test/test_files/copy/copy_to_csv.test (hunk 2 above)
Comment (mxwli) [reply test/test_files/copy/copy_to_csv.test:12]: Yes. Real values are scanned as decimals by default, and this is how the formatting works for decimals.

File: src/processor/operator/persistent/reader/reader_bind_utils.cpp (hunk 3 above)
Comment (mxwli) [reply src/processor/operator/persistent/reader/reader_bind_utils.cpp:27]: The reason I changed this is because previously, a test was giving an error because `COPY table FROM csv` failed the check in this part of the code. I think I'll disable sniffing if we're expecting types.

File: src/function/cast_string_non_nested_functions.cpp (hunk 8 above)
Comment (mxwli) [reply src/function/cast_string_non_nested_functions.cpp:92]: We support all three formats. I have a test for each in `date.csv`

File: src/common/types/types.cpp (hunk 1 above)
Comment (mxwli) [reply src/common/types/types.cpp:1804]: CombineTypes combines to STRING as the widest type. I'll add this as a comment.

File: src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp (hunk 4 above)
Comment (mxwli) [reply src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp:35]: empty lists, empty rows, etc. are resolved to ANY type, which should be removed.

File: src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp (hunk 5 above)
Comment (mxwli) [reply src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp:37]: You're right

File: src/processor/operator/persistent/reader/csv/driver.cpp (hunk 6 above)
Comment (mxwli) [reply src/processor/operator/persistent/reader/csv/driver.cpp:95]: If you mean CSVs with delimiters & line breakers inside elements, I think we'll be able to handle that. That part of the code is separate from the driver.

File: src/function/cast_string_non_nested_functions.cpp (hunk 10 above)
Comment (mxwli) [reply src/function/cast_string_non_nested_functions.cpp:142]: UUID I can support, but intervals are trickier. I could write a regex for matching intervals, but it could be quite complex, and I couldn't guarantee for it to be valid. The current casting from string to interval doesn't support any form of `tryCast`. Instead, it casts and throws an exception when it can't, so I can't use that unless I want a performance hit to sniffing.

File: src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp (hunk 5 above)
Comment (mxwli) [reply src/processor/operator/persistent/reader/csv/serial_csv_reader.cpp]: Nevermind, std::move is necessary because you can't copy logical types.

File: src/function/cast_string_non_nested_functions.cpp (hunk 8 above)
Comment (acquamarin) [reply src/function/cast_string_non_nested_functions.cpp:92]: I think we support those separators:
```
    if (sep != ' ' && sep != '-' && sep != '/' && sep != '\\') {
        // invalid separator
        return false;
    }
```
Can you add those separators there?

**Review by acquamarin — COMMENTED** [review]
Can you try the following csv and query:
looks like the casting betweeen int64 and int128 is not properly defined:
this is my csv file:
```
1
9423372036854775807
```
query:
```
kuzu> load from '1.csv'(sample_size=3) return * ;
Stack trace (most recent call first):
#0  0x10439fa0b0000000 in void kuzu::function::simpleIntegerCast<long long, true>(char const*, unsigned long long, long long&, kuzu::common::LogicalTypeID) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#1  0x10450faf30000000 in kuzu::function::CastString::copyStringToVector(kuzu::common::ValueVector*, unsigned long long, std::__1::basic_string_view<char, std::__1::char_traits<char>>, kuzu::common::CSVOption const*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#2  0x104794a870000000 in kuzu::processor::ParsingDriver::addValue(unsigned long long, unsigned int, std::__1::basic_string_view<char, std::__1::char_traits<char>>) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#3  0x104790b930000000 in unsigned long long kuzu::processor::BaseCSVReader::parseCSV<kuzu::processor::ParallelParsingDriver>(kuzu::processor::ParallelParsingDriver&) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#4  0x1047968db0000000 in kuzu::processor::ParallelCSVReader::parseBlock(unsigned long long, kuzu::common::DataChunk&) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#5  0x1047974770000000 in kuzu::processor::tableFunc(kuzu::function::TableFuncInput&, kuzu::function::TableFuncOutput&) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#6  0x10482e3470000000 in kuzu::processor::TableFunctionCall::getNextTuplesInternal(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#7  0x1048275f70000000 in kuzu::processor::PhysicalOperator::getNextTuple(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#8  0x10482857f0000000 in kuzu::processor::Projection::getNextTuplesInternal(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#9  0x1048275f70000000 in kuzu::processor::PhysicalOperator::getNextTuple(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#10 0x104829c770000000 in kuzu::processor::ResultCollector::executeInternal(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#11 0x1048393670000000 in kuzu::processor::ProcessorTask::run() at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#12 0x10438ee7b0000000 in kuzu::common::TaskScheduler::runTask(kuzu::common::Task*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#13 0x10438f83b0000000 in kuzu::common::TaskScheduler::runWorkerThread() at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#14 0x10438fa830000000 in void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, kuzu::common::TaskScheduler::TaskScheduler(unsigned long long)::$_0>>(void*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#15 0x1887eef930000000 at /usr/lib/system/libsystem_pthread.dylib
Stack trace (most recent call first):
#0  0x104794c3b0000000 in kuzu::processor::ParsingDriver::addValue(unsigned long long, unsigned int, std::__1::basic_string_view<char, std::__1::char_traits<char>>) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#1  0x104790b930000000 in unsigned long long kuzu::processor::BaseCSVReader::parseCSV<kuzu::processor::ParallelParsingDriver>(kuzu::processor::ParallelParsingDriver&) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#2  0x1047968db0000000 in kuzu::processor::ParallelCSVReader::parseBlock(unsigned long long, kuzu::common::DataChunk&) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#3  0x1047974770000000 in kuzu::processor::tableFunc(kuzu::function::TableFuncInput&, kuzu::function::TableFuncOutput&) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#4  0x10482e3470000000 in kuzu::processor::TableFunctionCall::getNextTuplesInternal(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#5  0x1048275f70000000 in kuzu::processor::PhysicalOperator::getNextTuple(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#6  0x10482857f0000000 in kuzu::processor::Projection::getNextTuplesInternal(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#7  0x1048275f70000000 in kuzu::processor::PhysicalOperator::getNextTuple(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#8  0x104829c770000000 in kuzu::processor::ResultCollector::executeInternal(kuzu::processor::ExecutionContext*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#9  0x1048393670000000 in kuzu::processor::ProcessorTask::run() at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#10 0x10438ee7b0000000 in kuzu::common::TaskScheduler::runTask(kuzu::common::Task*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#11 0x10438f83b0000000 in kuzu::common::TaskScheduler::runWorkerThread() at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#12 0x10438fa830000000 in void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, kuzu::common::TaskScheduler::TaskScheduler(unsigned long long)::$_0>>(void*) at /Users/z473chen/Desktop/code/kuzu/build/relwithdebinfo/tools/shell/kuzu
#13 0x1887eef930000000 at /usr/lib/system/libsystem_pthread.dylib
Error: Copy exception: Error in file 1.csv on line 2: Conversion exception: Cast failed. Could not convert "9423372036854775807" to INT64.
```
We should snif this column as int128 instead of int64.

**Review by acquamarin — COMMENTED** [review]
For a csv like this:
We should snif this as double instead of decimal:
```
1
942.45212414
```

File: src/function/cast_string_non_nested_functions.cpp [hunk 13]
```diff
@@ -83,5 +88,151 @@ bool TryCastStringToTimestamp::tryCast<timestamp_sec_t>(const char* input, uint6
...
+        return LogicalType::DATE();
+    }
+    // it might just be quicker to try cast to timestamp
```
Comment (acquamarin) [inline src/function/cast_string_non_nested_functions.cpp:205]: Our comment always starts with a capital letter, and ends with a period.

File: src/function/cast_string_non_nested_functions.cpp [hunk 14]
```diff
@@ -83,5 +88,151 @@ bool TryCastStringToTimestamp::tryCast<timestamp_sec_t>(const char* input, uint6
...
+        return LogicalType::UUID();
+    }
+
+    // interval checking
+    if (isInterval(cpy)) {
+        return LogicalType::INTERVAL();
+    }
+
+    if (cpy.front() == array_begin && cpy.back() == array_end) {
+        auto split = StringUtils::split(cpy.substr(1, cpy.size() - 2), ",", false);
```
Comment (acquamarin) [inline src/function/cast_string_non_nested_functions.cpp:222]: Add comment for false variable

File: src/function/cast_string_non_nested_functions.cpp [hunk 15]
```diff
@@ -83,5 +88,151 @@ bool TryCastStringToTimestamp::tryCast<timestamp_sec_t>(const char* input, uint6
...
+        auto childType = LogicalType::ANY();
+        for (auto& ele : split) {
+            childType = LogicalTypeUtils::combineTypes(childType, inferMinimalTypeFromString(ele));
+        }
+        return LogicalType::LIST(std::move(childType));
+    }
+
+    if (cpy.front() == '{' && cpy.back() == '}') {
```
Comment (acquamarin) [inline src/function/cast_string_non_nested_functions.cpp:230]: is this correct? What if the infermapOrStruct fails?
If i have a string like: "{abc}", will this be interpreted as string or struct?

**Review by acquamarin — COMMENTED** [review]
I found some bugs with nested types:
1. Should be interpreted as int64[][]
```
kuzu> load from 'test1.csv' return *;
┌───────────┐
│ column0   │
│ STRING[]  │
├───────────┤
│ [[]]      │
│ [[5,2,3]] │
└───────────┘
(2 tuples)
(1 column)
Time: 0.91ms (compiling), 0.37ms (executing)
➜  kuzu git:(csv-sniffing) ✗ cat test1.csv
"[[]]"
"[[5,2,3]]"
```
2. struct infer rule:
```
➜  kuzu git:(csv-sniffing) ✗ ./build/release/tools/shell/kuzu dasdsa
Opened the database at path: dasdsa in read-write mode.
Enter ":help" for usage hints.
kuzu> load from 'test2.csv' return *;
Error: Parser exception: Invalid struct field name: a
➜  kuzu git:(csv-sniffing) ✗ cat test2.csv
"{'a': dssadad, 'b': asd}"
```

File: src/function/cast_string_non_nested_functions.cpp (hunk 15 above)
Comment (mxwli) [reply src/function/cast_string_non_nested_functions.cpp:230]: It'll give a string.

**Comment by mxwli** [comment]
I should note that the default interpretation of `{}` is map. The reason behind this is that maps are variable sized, and structs are not. The main problem this may cause is that if we have the following struct column
```
{a: 1, b: 2}
{}
```
Then the inference system will conclude that the column is a `STRING`. This problem occurs with map columns if we default interpret as struct too. It's just more likely for `{}` to refer to a map rather than a struct.

**Review by acquamarin — APPROVED** [review]
