### PR TITLE
Fix issue 1738

### LINKED ISSUE #1738: Throw copy exception when num of columns in files are not matched with num of properties in table schema
We should throw an exception when the num of columns in files are not expected, i.e., not matched with the num of properties defined in table schema.

### PR DESCRIPTION
**Pull request by acquamarin**
Fix #1738

### CODE REVIEW

File: src/processor/mapper/map_ddl.cpp [hunk 1]
```diff
@@ -79,16 +79,17 @@ std::unique_ptr<PhysicalOperator> PlanMapper::mapLogicalCopyNodeToPhysical(Logic
...
-                    catalog->getReadOnlyVersion()->getNodeTableSchema(copy->getTableID()),
-                    copy->getCopyDescription().filePaths);
+                    nodeTableSchema, copy->getCopyDescription().filePaths);
             readFile = std::make_unique<ReadCSV>(arrowColumnPoses, offsetVectorPos,
                 readFileSharedState, getOperatorID(), copy->getExpressionsForPrinting());
         } else {
-            readFileSharedState =
-                std::make_shared<ReadParquetSharedState>(copy->getCopyDescription().filePaths);
+            readFileSharedState = std::make_shared<ReadParquetSharedState>(
+                copy->getCopyDescription().filePaths, nodeTableSchema);
```
Comment (andyfengHKU) [inline src/processor/mapper/map_ddl.cpp:92]: Let's be consistent and put nodeTableSchema always before/after filePaths for CSVState and ParquetState

**Review by andyfengHKU — APPROVED** [review]
