### PR TITLE
Fold default value when add property

### LINKED ISSUE #4782: Bug: Default values when adding new columns doesn't work if casting of a literal is required
### Kùzu version

master

### What operating system are you using?

Ubuntu 22

### What happened?

Idea is similar to https://github.com/kuzudb/kuzu/issues/4389. Consider the queries:
```
create node table Person(id INT64, PRIMARY KEY (id))
create rel table likes (from person to person);
alter table likes add years int32 default 0
```

The query `alter table likes add years int32 default 0` will fail with the message 
```
Runtime exception: Cannot set a non-constant default value when adding columns on REL tables.
```
This is because the literal `0` needs to be casted from int64 to int32, and we don't consider the casted value a constant.

Similarly, the statement `alter table likes add years float default 5.4` will also fail.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by andyfengHKU**
# Description

Fix #4782

### CODE REVIEW

File: src/binder/bind/bind_ddl.cpp [hunk 1]
```diff
@@ -47,57 +47,35 @@ static void validatePropertyName(const std::vector<PropertyDefinition>& definiti
...
-        throw BinderException(ExceptionMessage::invalidPKType(type.toString()));
+std::unique_ptr<parser::ParsedExpression> Binder::resolvePropertyDefault(
+    ParsedExpression* parsedDefault, const common::LogicalType& type, const std::string& tableName,
+    const std::string& propertyName) {
+    if (parsedDefault == nullptr) { // No default provided.
+        if (type.getLogicalTypeID() == LogicalTypeID::SERIAL) {
+            auto serialName = SequenceCatalogEntry::getSerialName(tableName, propertyName);
+            return ParsedExpressionUtils::getSerialDefaultExpr(serialName);
+        } else {
+            return std::make_unique<ParsedLiteralExpression>(Value::createNullValue(type), "NULL");
```
Comment (acquamarin) [inline src/binder/bind/bind_ddl.cpp:72]: Add a comment for NULL?

**Review by acquamarin — APPROVED** [review]
