### PR TITLE
Nested alias

### LINKED ISSUE #4132: Bug: SNB IC1 binding error with "Cannot evaluate expression with type PROPERTY"
### Kùzu version

0.6.0

### What operating system are you using?

MacOS Sonoma

### What happened?

The following query fails with a binding error `Cannot evaluate expression with type PROPERTY`, which shouldn't be triggered.
```cypher
MATCH (p:Person {id: 933}), (friend:Person {firstName: 'Carmen'})
       WHERE NOT p.id=friend.id
       WITH p, friend
       MATCH path = (p)-[:KNOWS* SHORTEST 1..3]-(friend)
       WITH min(length(path)) AS distance, friend, friend.lastName as friendLastName, friend.id as friendID
ORDER BY
    distance ASC,
    friendLastName ASC,
    friendID ASC
LIMIT 20
MATCH (friend)-[:IS_LOCATED_IN]->(friendCity:Place {type: 'city'})
OPTIONAL MATCH (friend)-[studyAt:STUDY_AT]->(uni:organisation {type: 'university'})-[:IS_LOCATED_IN]->(uniCity:Place {type: 'city'})
WITH friend, collect(
    CASE uni.name
        WHEN null THEN null
        ELSE [uni.name, cast(studyAt.classYear, 'string'), uniCity.name]
    END ) AS unis, friendCity, distance
OPTIONAL MATCH (friend)-[workAt:WORK_AT]->(company:organisation {type: 'company'})-[:IS_LOCATED_IN]->(companyCountry:Place {type: 'country'})
WITH friend, collect(
    CASE company.name
        WHEN null THEN null
        ELSE [company.name, cast(workAt.workFrom, 'string'), companyCountry.name]
    END ) AS companies, unis, friendCity, distance
RETURN
    friend.id AS friendId,
    friend.lastName AS friendLastName,
    distance AS distanceFromPerson,
    friend.birthday AS friendBirthday,
    friend.creationDate AS friendCreationDate,
    friend.gender AS friendGender,
    friend.browserUsed AS friendBrowserUsed,
    friend.locationIP AS friendLocationIp,
    friend.email AS friendEmails,
    friend.speaks AS friendLanguages,
    friendCity.name AS friendCityName,
    unis AS friendUniversities,
    companies AS friendCompanies
ORDER BY
    distanceFromPerson ASC,
    friendLastName ASC,
    friendId ASC
LIMIT 20
```

### Are there known steps to reproduce?

Run the above query. The dataset is attached [here]( https://drive.google.com/file/d/1hgzNwU3l0KmUGimY3xhynMAatddnjnl9/view?usp=share_link).

### PR DESCRIPTION
**Pull request by andyfengHKU**
# Description

Fix a bug where we cannot handle nested alias properly.

See the following test
```
-STATEMENT MATCH (a) WITH COUNT(a) AS b RETURN b AS c;
---- 1
14
```

Fixes #4132

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/binder/bind/bind_projection_clause.cpp [hunk 1]
```diff
@@ -24,41 +24,60 @@ namespace binder {
 // MATCH (a) WITH a._id RETURN a.age;
 // And then apply WithClauseProjectionRewriter after binding to rewrite as
 // MATCH (a) WITH a._id, a.age RETURN a.age
-static expression_vector rewriteProjectionInWithClause(const expression_vector& expressions) {
-    expression_vector result;
-    for (auto& expression : expressions) {
+// TODO(Xiyang): this rewrite is creating problem for alias handling. Consider move this out of
```
Comment (ray6080) [inline src/binder/bind/bind_projection_clause.cpp:27]: Can u be more specific here? What does `this` refer to?

**Review by ray6080 — APPROVED** [review]
