### PR TITLE
Rollback hash index checkpoint

### LINKED ISSUE #4338: Buffer manager allocation failures causing corruption
E.g. the test `CopyTest.OutOfMemoryRecovery` (renamed to CopyTest.DISABLED_OutOfMemoryRecovery` in #4188) runs out of memory when committing (at the time of #4188) and then corrupts the database since the node group is constructed in two parts.
Generally I think we need to be more careful about potential allocation failures and try to ensure that newly allocated objects are isolated until we're done creating them to minimize the side-effects of failure.

The issue in that test in particular is that we add a new node group object to the node group collection, but don't allocate the `persistentChunkGroup` field until later. If that doesn't end up being allocated due to an exception, we will handle the exception, and then when closing the database serialize the node groups, including the one that was incomplete (which currently serializes fine the first time, but has issues after that).
It's worth noting that this particular situation is not actually unrecoverable at the moment, the other test in that file still succeeds by dropping the table.

One option for further testing of this problem in general would be to repeatedly try something, e.g. a reasonable sized-copy, and set up the buffer manager to randomly fail (or fail after `n` allocations if we want to be more exhaustive) as if it is out of memory and make sure we can recover.

### PR DESCRIPTION
**Pull request by royi-luo**
# Description

Fixes #4338 

- Separate execute/commit and checkpoint in `ClientContext::executeNoLock()` into separate catch statements which avoids us triggering rollback of a committed statement if an error occurs during checkpoint.
- Rollback changes made to PK index during checkpoint if an exception occurs so that the checkpoint can be retried successfully

# Contributor agreement

- [ ] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/main/client_context.cpp [hunk 1]
```diff
@@ -504,16 +506,28 @@ std::unique_ptr<QueryResult> ClientContext::executeNoLock(PreparedStatement* pre
...
+    if (autoCommitTriggered) {
+        try {
+            this->transactionContext->autoCheckpointIfNeeded();
+        } catch (common::CheckpointException& e) {
+            auto locks = e.getLocks();
+            this->transactionContext->rollbackCheckpoint(locks);
+            return handleFailedExecute(executionContext.get(), e);
+        } catch (std::exception& e) {
+            // exception was before checkpoint started, no need to rollback checkpoint
+            return handleFailedExecute(executionContext.get(), e);
```
Comment (royi-luo) [inline src/main/client_context.cpp:527]: add test to cover this

File: test/copy/copy_test.cpp [hunk 2]
```diff
@@ -247,6 +258,70 @@ TEST_F(CopyTest, RelInsertBMExceptionDuringCommitRecovery) {
...
+            },
+        .executeFunc =
+            [](main::Connection* conn, int) {
+                return conn->query(common::stringFormat(
+                    "UNWIND RANGE(1,{}) AS i CREATE (a:account {ID:i})", numValues));
+            },
+        .earlyExitOnFailureFunc =
+            [this](main::QueryResult*) {
+                // make sure the checkpoint when closing the DB doesn't fail
+                failureFrequency = UINT64_MAX;
```
Comment (royi-luo) [inline test/copy/copy_test.cpp:316]: can remove this

File: src/transaction/transaction_manager.cpp [hunk 3]
```diff
@@ -152,28 +183,37 @@ void TransactionManager::checkpointNoLock(main::ClientContext& clientContext) {
...
+        // Clear the wal, and also shadowing files.
+        wal.clearWAL();
+        clientContext.getStorageManager()->getShadowFile().clearAll(clientContext);
+        StorageUtils::removeWALVersionFiles(clientContext.getDatabasePath(),
+            clientContext.getVFSUnsafe());
+    } catch (std::exception& e) {
+        // since we want to rollback the checkpoint atomically
+        // we maintain ownership of the locks (which we will release when we are done handling the
+        // exception)
+        common::CheckpointException checkpointException(e);
```
Comment (ray6080) [inline src/transaction/transaction_manager.cpp:213]: Can we not handle rollback here? instead of back to ClientContext? so lots of things can be simplified.

Comment (royi-luo) [reply src/transaction/transaction_manager.cpp:213]: that's probably a good idea

Comment (royi-luo) [reply src/transaction/transaction_manager.cpp]: updated

File: src/include/common/exception/checkpoint_exception.h [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+    std::vector<const common::UniqLock*> getLocks() const {
+        std::vector<const common::UniqLock*> ret;
+        for (const auto& lock : locks) {
+            ret.push_back(lock.get());
+        }
+        return ret;
+    }
+
+private:
+    std::vector<std::shared_ptr<common::UniqLock>> locks;
```
[the remark this answers is not in the document]
Comment (royi-luo) [reply src/include/common/exception/checkpoint_exception.h]: removed since we handle the rollback in the transaction manager

File: src/include/transaction/transaction_context.h [hunk 5]
```diff
@@ -5,6 +5,10 @@
 #include "transaction.h"
 
 namespace kuzu {
+namespace common {
+struct UniqLock;
```
Comment (ray6080) [inline src/include/transaction/transaction_context.h:9]: Do we need this forward declaration?

File: src/storage/index/hash_index.cpp [hunk 6]
```diff
@@ -485,6 +491,12 @@ PrimaryKeyIndex::PrimaryKeyIndex(const DBFileIDAndName& dbFileIDAndName, bool re
             }
         },
         [&](auto) { KU_UNREACHABLE; });
+
+    if (newIndex && !inMemMode) {
+        // checkpoint the creation of the index so that if we need to rollback it will be to a
+        // state we can retry from (an empty index with the disk arrays initialized)
+        checkpoint(true);
```
Comment (ray6080) [inline src/storage/index/hash_index.cpp:498]: Add inline comment for `true` here.

File: src/include/main/client_context.h [hunk 7]
```diff
@@ -177,6 +177,9 @@ class KUZU_API ClientContext {
 
     void runFuncInTransaction(const std::function<void(void)>& fun);
 
+    std::unique_ptr<QueryResult> handleFailedExecute(processor::ExecutionContext* executionContext,
```
Comment (ray6080) [inline src/include/main/client_context.h:180]: `handleFailedExecute` -> `handleFailedExecution` / `handleExecutionError`

File: src/main/client_context.cpp [hunk 8]
```diff
@@ -504,16 +505,23 @@ std::unique_ptr<QueryResult> ClientContext::executeNoLock(PreparedStatement* pre
...
     } catch (std::exception& e) {
         transactionContext->rollback();
-        getMemoryManager()->getBufferManager()->getSpillerOrSkip(
-            [](auto& spiller) { spiller.clearFile(); });
-        progressBar->endProgress(executionContext->queryID);
-        return queryResultWithError(e.what());
+        return handleFailedExecute(executionContext.get(), e);
+    }
+
+    if (autoCommitTriggered) {
```
Comment (ray6080) [inline src/main/client_context.cpp:517]: I wonder if you can throw a CheckpointException and catch here instead of explicitly separating autoCheckpoint and commit in different places.

**Review by ray6080 — COMMENTED** [review]
@benjaminwinger can you also take a look at changes to hash index and overflow file?

File: src/main/client_context.cpp (hunk 8 above)
Comment (royi-luo) [reply src/main/client_context.cpp:517]: probably a good idea, that should clean up the changes quite a bit

File: src/include/transaction/transaction_context.h (hunk 5 above)
Comment (royi-luo) [reply src/include/transaction/transaction_context.h]: removed

File: src/main/client_context.cpp (hunk 8 above)
Comment (royi-luo) [reply src/main/client_context.cpp]: updated

File: src/storage/index/hash_index.cpp [hunk 9]
```diff
@@ -425,7 +431,7 @@ PrimaryKeyIndex::PrimaryKeyIndex(const DBFileIDAndName& dbFileIDAndName, bool re
                                       vfs, context)},
       dbFileIDAndName{dbFileIDAndName}, shadowFile{*shadowFile} {
     KU_ASSERT(!(inMemMode && readOnly));
-    bool newIndex = fileHandle->getNumPages() == 0;
+    bool newIndex = (fileHandle->getNumPages() == 0);
```
[the remark this answers is not in the document]
Comment (royi-luo) [reply src/storage/index/hash_index.cpp]: updated

**Review by ray6080 — APPROVED** [review]
