### PR TITLE
Skip limit parameter

### LINKED ISSUE #4704: Feature: Support SKIP/LIMIT with language clients
### Kùzu version

0.7.1

### What operating system are you using?

Windows

### What happened?

Use of parameters for LIMIT/SKIP clauses with the Java client seems to be failing with error: Binder exception: The number of rows to skip/limit must be a non-negative integer. 
See below a small example highlighting the issue:
```
 String query = "MATCH (s) RETURN s ORDER BY OFFSET(ID(s)) SKIP $skip LIMIT $size";

        PreparedStatement statement;
        try {
            Map<String, Value> params = new HashMap<>();
            params.put("skip", new Value((int) 5));
            params.put("size", new Value((int) 5));
            statement = kuzuConnection.prepare(query);
            try (com.kuzudb.QueryResult result = kuzuConnection.execute(statement, params)) {
                if (result.isSuccess()) {
                    InitializeQueryResult(result);
                } else {
                    String error = result.getErrorMessage();
                    var test = "lol";
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (ObjectRefDestroyedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
```

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by acquamarin**
closes #4704
This PR allows user to write parameter expression as limit/skip number.
Instead of binding the limit/skip number at runtime, we are going to evaluate and bind at run time.
example:
```
auto prepared = conn->prepare("MATCH (p:person) RETURN p.ID skip $sp");
auto result = conn->execute(prepared.get(), std::make_pair(std::string{"sp"}, 2));
```

### CODE REVIEW

File: src/binder/bind/bind_projection_clause.cpp [hunk 1]
```diff
@@ -251,33 +250,14 @@ bool Binder::isOrderByKeyTypeSupported(const LogicalType& dataType) {
     return true;
 }
 
-uint64_t Binder::bindSkipLimitExpression(const ParsedExpression& expression) {
+std::shared_ptr<Expression> Binder::bindSkipLimitExpression(const ParsedExpression& expression) {
     auto boundExpression = expressionBinder.bindExpression(expression);
-    auto errorMsg = "The number of rows to skip/limit must be a non-negative integer.";
-    if (boundExpression->expressionType != ExpressionType::LITERAL) {
-        throw BinderException(errorMsg);
+    if (boundExpression->expressionType != ExpressionType::LITERAL &&
```
Comment (andyfengHKU) [inline src/binder/bind/bind_projection_clause.cpp:255]: I have a wild idea.

Can we keep limit/skip number as `int64_t`. 

When expr is of type LITERAL, we set skip/limit properly.
When expr is of type PARAMETER, if PARAMETER is set, we set skip/limit property. If not set, we set them to 0 or 1 or some constant. Since we will always rebind with prepare this seems fine?

Also we should probably also support when expr is a foldable constant, something like 1 + 2

File: src/planner/operator/logical_limit.cpp [hunk 2]
```diff
@@ -1,20 +1,82 @@
...
 namespace kuzu {
 namespace planner {
 
+static uint64_t getLiteralNumber(std::shared_ptr<kuzu::binder::Expression> expr) {
+    uint64_t number = common::INVALID_LIMIT;
+    if (expr == nullptr) {
+        return number;
+    }
+    auto value = common::Value::createDefaultValue(expr->dataType);
+    switch (expr->expressionType) {
```
Comment (andyfengHKU) [inline src/planner/operator/logical_limit.cpp:18]: I see multiple place where we have 

```
switch expressionType
case LITERAL
case PARAMETER
return value
```

This is at least the case for query_fts_index, query_hnsw_index and here. If so, we should refactor.

If you decide to take my wild idea, ignore this comment.

**Review by andyfengHKU — APPROVED** [review]
