### PR TITLE
Fix issue-3785

### LINKED ISSUE #3785: Bug: `MATCH` path with recursive relation returns nodes/rels in wrong order
### Kùzu version

0.4.2

### What operating system are you using?

Fedora 39

### What happened?

`MATCH`ing all paths from any user to `:City {name: "Guelph"}` via
```cypher
MATCH p = (u:User)-[e*]->(c:City {name: "Guelph"}) 
RETURN properties(nodes(p),'name'), properties(rels(p),'_label');
```
returns
```
["Noura","Guelph"]	["LivesIn"]
["Zhang","Noura","Guelph"]	["LivesIn","Follows"]
["Adam","Noura","Zhang","Guelph"]	["LivesIn","Follows","Follows"]
["Karissa","Noura","Zhang","Guelph"]	["LivesIn","Follows","Follows"]
["Adam","Noura","Zhang","Karissa","Guelph"]	["LivesIn","Follows","Follows","Follows"]
```
, which doesn't reflect nodes and rel order in graph:
screenshot

(demo dataset)

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by andyfengHKU**
# Description

Fixes #3785 

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/binder/bind/bind_graph_pattern.cpp [hunk 1]
```diff
@@ -374,7 +374,7 @@ std::shared_ptr<RelExpression> Binder::createRecursiveQueryRel(const parser::Rel
     auto nodeCopy = createQueryNode(recursivePatternInfo->nodeName,
         std::vector<table_id_t>{nodeTableIDs.begin(), nodeTableIDs.end()});
     // Bind intermediate rel
-    auto rel = createNonRecursiveQueryRel(recursivePatternInfo->relName, tableIDs, node, nodeCopy,
+    auto rel = createNonRecursiveQueryRel(recursivePatternInfo->relName, tableIDs, nullptr, nullptr,
```
Comment (ray6080) [inline src/binder/bind/bind_graph_pattern.cpp:377]: Add inline comments for nullptr as usual.

File: src/include/processor/operator/recursive_extend/frontier_scanner.h [hunk 2]
```diff
@@ -64,9 +64,11 @@ class PathScanner : public BaseFrontierScanner {
 public:
     PathScanner(TargetDstNodes* targetDstNodes, size_t k,
         std::unordered_map<common::table_id_t, std::string> tableIDToName,
-        path_semantic_check_t semanticCheckFunc, common::ExtendDirection extendDirection)
+        path_semantic_check_t semanticCheckFunc, common::ExtendDirection extendDirection,
```
Comment (ray6080) [inline src/include/processor/operator/recursive_extend/frontier_scanner.h:67]: didn't notice this. but isn't `path_semantic_check_func` easier to understand than `path_semantic_check_t`?

File: src/processor/operator/recursive_extend/frontier_scanner.cpp [hunk 3]
```diff
@@ -122,12 +122,25 @@ void PathScanner::initDfs(const node_rel_id_t& nodeAndRelID, size_t currentDepth
...
+}
+
+void PathScanner::writePathRel(common::internalID_t relID, RecursiveJoinVectors& vectors,
+    sel_t vectorPos) {
+    vectors.pathRelsIDDataVector->setValue<relID_t>(vectorPos, relID);
+    StringVector::addString(vectors.pathRelsLabelDataVector, vectorPos,
+        tableIDToName.at(relID.tableID));
 }
 
 void PathScanner::writePathToVector(RecursiveJoinVectors* vectors, sel_t& vectorPos,
```
Comment (ray6080) [inline src/processor/operator/recursive_extend/frontier_scanner.cpp:146]: Trivial comment: I think you may want to pass in `RecursiveJoinVectors&` instead of `RecursiveJoinVectors*`.

File: src/processor/operator/recursive_extend/frontier_scanner.cpp [hunk 4]
```diff
@@ -145,49 +158,66 @@ void PathScanner::writePathToVector(RecursiveJoinVectors* vectors, sel_t& vector
...
         }
-    } else if (extendDirection == ExtendDirection::FWD) {
-        for (auto i = 0u; i < k; ++i) {
-            auto srcNodeID = nodeIDs[i];
-            auto dstNodeID = nodeIDs[i + 1];
-            auto relID = relIDs[i];
-            writePathRels(vectors, relIDDataVectorPos, srcNodeID, dstNodeID, relID,
-                tableIDToName.at(relID.tableID));
-            relIDDataVectorPos++;
+        if (extendDirection == ExtendDirection::FWD) {
```
Comment (ray6080) [inline src/processor/operator/recursive_extend/frontier_scanner.cpp:166]: I'd prefer `switch` statement here compared to `if`.

**Review by ray6080 — APPROVED** [review]
