### PR TITLE
Fix unordered_map at error caused by non-existing expression in factorized group

### LINKED ISSUE #4716: Bug: Error: unordered_map::at thrown by Kuzu
### Kùzu version

v0.7.1

### What operating system are you using?

Ubuntu 22.04

### What happened?

Hi! I found that Kuzu DB gives an unexpected exception when processing the query. Steps to reproduce are as follows.
1. Use the following queries to initialize the database.
```cypher
CREATE NODE TABLE L0 (k0 STRING, k1 STRING, k2 BOOLEAN, k3 INT64, k4 INT64, k5 BOOLEAN, k6 BOOLEAN, id INT64, PRIMARY KEY (id));
CREATE NODE TABLE L1 (k7 INT64, k8 STRING, k9 STRING, k10 BOOLEAN, k11 INT64, id INT64, PRIMARY KEY (id));
CREATE NODE TABLE L2 (k12 INT64, k13 BOOLEAN, k14 INT64, k15 BOOLEAN, k16 BOOLEAN, k17 BOOLEAN, id INT64, PRIMARY KEY (id));
CREATE NODE TABLE L3 (k18 STRING, k19 INT64, k20 INT64, k21 STRING, k22 STRING, k23 BOOLEAN, id INT64, PRIMARY KEY (id));
CREATE NODE TABLE L4 (k24 STRING, k25 BOOLEAN, k26 BOOLEAN, k27 INT64, k28 BOOLEAN, k29 INT64, k30 INT64, id INT64, PRIMARY KEY (id));
CREATE NODE TABLE L5 (k31 BOOLEAN, k32 INT64, k33 BOOLEAN, k34 STRING, k35 BOOLEAN, k36 INT64, id INT64, PRIMARY KEY (id));
CREATE NODE TABLE L6 (k37 STRING, k38 INT64, k39 BOOLEAN, k40 INT64, k41 BOOLEAN, k42 STRING, id INT64, PRIMARY KEY (id));
CREATE NODE TABLE L7 (k43 BOOLEAN, k44 STRING, k45 BOOLEAN, k46 INT64, k47 INT64, id INT64, PRIMARY KEY (id));
CREATE REL TABLE T0 (FROM L0 TO L6, k48 STRING, k49 STRING, k50 INT64, k51 STRING, k52 BOOLEAN, k53 INT64, id INT64);
CREATE REL TABLE T1 (FROM L0 TO L4, k54 BOOLEAN, k55 BOOLEAN, k56 INT64, k57 STRING, k58 BOOLEAN, id INT64);
CREATE REL TABLE T2 (FROM L3 TO L2, k59 STRING, k60 BOOLEAN, k61 BOOLEAN, k62 STRING, k63 STRING, id INT64);
CREATE REL TABLE T3 (FROM L3 TO L6, k64 INT64, k65 BOOLEAN, k66 INT64, k67 STRING, k68 BOOLEAN, k69 INT64, id INT64);
CREATE REL TABLE T4 (FROM L5 TO L6, k70 STRING, k71 BOOLEAN, k72 BOOLEAN, k73 INT64, k74 BOOLEAN, id INT64);
CREATE REL TABLE T5 (FROM L4 TO L1, k75 BOOLEAN, k76 INT64, k77 INT64, k78 INT64, k79 STRING, k80 BOOLEAN, k81 BOOLEAN, id INT64);
CREATE REL TABLE T6 (FROM L0 TO L2, k82 BOOLEAN, k83 INT64, k84 BOOLEAN, k85 BOOLEAN, k86 BOOLEAN, k87 INT64, id INT64);
CREATE REL TABLE T7 (FROM L5 TO L4, k88 BOOLEAN, k89 INT64, k90 STRING, k91 INT64, k92 STRING, id INT64);
CREATE REL TABLE T8 (FROM L5 TO L4, k93 BOOLEAN, k94 INT64, k95 INT64, k96 INT64, k97 BOOLEAN, id INT64);
CREATE REL TABLE T9 (FROM L3 TO L1, k98 STRING, k99 INT64, k100 INT64, k101 STRING, k102 STRING, k103 STRING, k104 BOOLEAN, id INT64);
CREATE REL TABLE T10 (FROM L0 TO L3, k105 INT64, k106 STRING, k107 BOOLEAN, k108 STRING, k109 INT64, id INT64);
CREATE REL TABLE T11 (FROM L3 TO L1, k110 BOOLEAN, k111 INT64, k112 BOOLEAN, k113 BOOLEAN, k114 INT64, k115 BOOLEAN, k116 STRING, id INT64);
CREATE REL TABLE T12 (FROM L1 TO L1, k117 STRING, k118 BOOLEAN, k119 BOOLEAN, k120 STRING, k121 STRING, id INT64);
CREATE REL TABLE T13 (FROM L2 TO L4, k122 BOOLEAN, k123 INT64, k124 STRING, k125 STRING, k126 STRING, k127 BOOLEAN, id INT64);
CREATE REL TABLE T14 (FROM L1 TO L3, k128 STRING, k129 BOOLEAN, k130 INT64, k131 BOOLEAN, k132 BOOLEAN, id INT64);
CREATE REL TABLE T15 (FROM L3 TO L0, k133 INT64, k134 INT64, k135 INT64, k136 STRING, k137 STRING, k138 STRING, k139 BOOLEAN, id INT64);
CREATE REL TABLE T16 (FROM L1 TO L5, k140 BOOLEAN, k141 BOOLEAN, k142 STRING, k143 BOOLEAN, k144 INT64, k145 STRING, k146 BOOLEAN, id INT64);
CREATE REL TABLE T17 (FROM L2 TO L5, k147 BOOLEAN, k148 BOOLEAN, k149 BOOLEAN, k150 BOOLEAN, k151 BOOLEAN, k152 BOOLEAN, id INT64);
CREATE REL TABLE T18 (FROM L4 TO L5, k153 BOOLEAN, k154 BOOLEAN, k155 STRING, k156 INT64, k157 STRING, k158 BOOLEAN, k159 INT64, id INT64);
CREATE REL TABLE T19 (FROM L4 TO L6, k160 BOOLEAN, k161 BOOLEAN, k162 STRING, k163 STRING, k164 BOOLEAN, k165 STRING, id INT64);
CREATE REL TABLE T20 (FROM L5 TO L3, k166 STRING, k167 BOOLEAN, k168 INT64, k169 STRING, k170 BOOLEAN, id INT64);
CREATE REL TABLE T21 (FROM L1 TO L4, k171 STRING, k172 STRING, k173 STRING, k174 BOOLEAN, k175 INT64, id INT64);
CREATE REL TABLE T22 (FROM L5 TO L0, k176 BOOLEAN, k177 INT64, k178 STRING, k179 INT64, k180 INT64, id INT64);
CREATE REL TABLE T23 (FROM L3 TO L6, k181 BOOLEAN, k182 STRING, k183 BOOLEAN, k184 INT64, k185 INT64, k186 STRING, id INT64);
CREATE REL TABLE T24 (FROM L3 TO L3, k187 BOOLEAN, k188 BOOLEAN, k189 INT64, k190 STRING, k191 STRING, k192 INT64, k193 BOOLEAN, id INT64);
CREATE REL TABLE T25 (FROM L3 TO L5, k194 BOOLEAN, k195 INT64, k196 INT64, k197 STRING, k198 STRING, k199 STRING, k200 BOOLEAN, id INT64);
CREATE REL TABLE T26 (FROM L3 TO L4, k201 STRING, k202 BOOLEAN, k203 INT64, k204 BOOLEAN, k205 INT64, k206 STRING, id INT64);
CREATE REL TABLE T27 (FROM L2 TO L3, k207 INT64, k208 STRING, k209 INT64, k210 INT64, k211 INT64, k212 BOOLEAN, id INT64);
CREATE REL TABLE T28 (FROM L2 TO L2, k213 INT64, k214 STRING, k215 BOOLEAN, k216 INT64, k217 BOOLEAN, k218 INT64, k219 STRING, id INT64);
CREATE REL TABLE T29 (FROM L6 TO L5, k220 INT64, k221 INT64, k222 INT64, k223 BOOLEAN, k224 BOOLEAN, k225 BOOLEAN, id INT64);
CREATE REL TABLE T30 (FROM L0 TO L0, k226 BOOLEAN, k227 BOOLEAN, k228 STRING, k229 BOOLEAN, k230 STRING, id INT64);
CREATE (n0 :L6{k39 : false, k38 : -4113470082403299178, k40 : -6068816160605443043, k42 : "m68jCl", k41 : true, id : 0, k37 : "s5fj9zTY0"});
CREATE (n0 :L0{k0 : "6DIEBd9", k1 : "kZYNS6f", k2 : true, k3 : -3002236845232900688, k4 : -9017766677436986206, k5 : true, k6 : true, id : 1});
CREATE (n0 :L1{k11 : -1304414193748854125, k10 : true, id : 2, k7 : -6078295915737455867, k8 : "IANiTeVTu", k9 : "LHhFupwZl"});
CREATE (n0 :L5{k31 : false, k33 : true, k32 : 1905998112509451819, id : 3, k35 : true, k34 : "L2XzulK9o", k36 : 3487060252057184409});
CREATE (n0 :L5{k31 : false, k33 : true, k32 : -609746112993269670, id : 4, k35 : false, k34 : "l0HWII2", k36 : 3336245918684372936});
CREATE (n0 :L6{k39 : false, k38 : -2356717711094391781, k40 : 960583289485226542, k42 : "2VOk7ZNUq", k41 : true, id : 5, k37 : "4Hcl8E6"});
CREATE (n0 :L1{k11 : -6113302254981707514, k10 : true, id : 6, k7 : -3812201220978385354, k8 : "f4ASz", k9 : "x363B"});
CREATE (n0 :L3{k19 : -4765855604282525597, k18 : "peY8u", k20 : 3282410403318157658, k22 : "rZq9c", k21 : "tGVFU5u", id : 7, k23 : false});
CREATE (n0 :L0{k0 : "F4Ji3hRN", k1 : "1u3V0g", k2 : false, k3 : -8995413594049600854, k4 : 7458953535878906945, k6 : false, id : 8});
MATCH (n0 {id : 8}), (n1 {id : 0}) CREATE(n0)-[r :T0{k49 : "gvKll", k51 : "ntV9Q", k50 : 1398527286434261433, k53 : -8724968450880799576, k52 : false, id : 9, k48 : "lhWb7"}]->(n1);
MATCH (n0 {id : 2}), (n1 {id : 4}) CREATE(n0)-[r :T16{k141 : true, k140 : true, k143 : true, k142 : "qExHGllvE", k145 : "rqwbTEZ3", k144 : 4820712555086524182, id : 10}]->(n1);
MATCH (n0 {id : 5}), (n1 {id : 3}) CREATE(n0)-[r :T29{k220 : 4143877186094010461, k222 : 8267880719597770095, k221 : 8500623340612532390, k224 : true, k223 : false, k225 : true, id : 11}]->(n1);
MATCH (n0 {id : 7}), (n1 {id : 2}) CREATE(n0)-[r :T11{k110 : true, k112 : true, k111 : 3427583982438366729, k114 : -8437460272362939397, k113 : true, k116 : "ypRrKdEf", k115 : true, id : 12}]->(n1);
MATCH (n0 {id : 3}), (n1 {id : 7}) CREATE(n0)-[r :T20{k167 : false, k166 : "tz4jO4ku", k169 : "T1KZDCF", k168 : -7936644163243621381, id : 13, k170 : true}]->(n1);
MATCH (n0 {id : 8}), (n1 {id : 1}) CREATE(n0)-[r :T30{k230 : "bZqVgcD", k226 : false, id : 14, k228 : "wfvk98P", k227 : false, k229 : true}]->(n1);
MATCH (n0 {id : 4}), (n1 {id : 7}) CREATE(n0)-[r :T20{k167 : true, k166 : "xpFqw", k168 : 6873511714324276725, id : 15, k170 : true}]->(n1);
MATCH (n0 {id : 0}), (n1 {id : 4}) CREATE(n0)-[r :T29{k220 : -4311353219591575617, k222 : -3135326396698055449, k221 : -4560314409849779690, k224 : true, k223 : false, k225 : true, id : 16}]->(n1);
MATCH (n0 {id : 6}), (n1 {id : 4}) CREATE(n0)-[r :T16{k141 : true, k140 : false, k143 : false, k142 : "pGeIzI8", k145 : "Y3BGQ", k144 : -7898518321111847146, k146 : false, id : 17}]->(n1);
```
2. The following query gives an exception "Error: unordered_map::at":
```cypher
MATCH (n0)-[r6]-(n1)<-[r7]-(n2)<-[r8]-(n3) WHERE true WITH n2 ORDER BY (n2.k33) LIMIT 1 WHERE (((((('Ir68oUyZr'+'kNiIX0WMt')+'SlFQWOKAV')+('L2idhdx9'+'s4ATzhAQU'))+'pV4a5Sz0') STARTS WITH 'Ir68oUyZrkNiIX0WMtSlFQWOKAVL2idhdx9s') AND ('dA524yw' CONTAINS (''+''))) MATCH (n0)<-[r9]-(n1)<-[r10]-(n2)-[r11]-(n3) WHERE true RETURN 1;
```
image

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by ray6080**
# Description

Fix #4716.

The test case exposes a problem when scanning multiple rel tables, we create one scan state for each, and this can leads to excessive unnecessary memory allocation due to scan state.
First, we should re-use scan state between rel tables. Second, we should make the scan state smaller, which I have a branch working on that already.

### CODE REVIEW

File: src/planner/operator/schema.cpp [hunk 1]
```diff
@@ -18,6 +18,7 @@ f_group_pos Schema::createGroup() {
 void Schema::insertToScope(const std::shared_ptr<Expression>& expression, f_group_pos groupPos) {
     KU_ASSERT(!expressionNameToGroupPos.contains(expression->getUniqueName()));
     expressionNameToGroupPos.insert({expression->getUniqueName(), groupPos});
+    KU_ASSERT(getGroup(groupPos)->expressionNameToPos.contains(expression->getUniqueName()));
```
Comment (andyfengHKU) [inline src/planner/operator/schema.cpp:21]: I wouldn't assert this. Instead the assertion already exist in `FactorizationGroup::getExpressionPos`

**Review by andyfengHKU — APPROVED** [review]

File: src/planner/operator/schema.cpp (hunk 1 above)
Comment (ray6080) [reply src/planner/operator/schema.cpp:21]: hmm I think the assertion in `FactorizationGroup::getExpressionPos` serves for a different purpose from this one.
