### PR TITLE
Better error message for copy

### LINKED ISSUE #2737: Better Python error handling message when (header=true) is not passed during `COPY FROM`
Consider a case where we're trying to insert `LivesIn` relations to an edge table:`(:Person)-[:LivesIn]->(:City)`

The data for the `lives_in.csv` is like this:

```
person_id,city_id
1,2
2,1
```

The following command is correct, and loads in the data when considering the header row.

```
COPY LivesIn FROM 'lives_in.csv' (header=true);
```

However, if the user forgets to specify the `(header=true)`clause, it will fail as expected, but the error message is not helpful:

```console
Traceback (most recent call last):
  File "/code/kuzu-debug/load_data.py", line 59, in <module>
    conn.execute(load_lives_in_edges)
  File "/code/kuzu-debug/.venv/lib/python3.11/site-packages/kuzu/connection.py", line 80, in execute
    _query_result = self._connection.execute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Conversion exception: Cast failed. person_id is not in INT64 range.
```

The above error message makes it seem like the data is incorrect, rather than something wrong with the way we specified it in the edge insertion query.

A better error message would be:

```
RuntimeError: Conversion exception: Cast failed. Expected INT64, got "person_id"
```

Stating it this way clearly states what the parser expects, and what it found, making user experience during debugging much better.

### PR DESCRIPTION
**Pull request by acquamarin**
Closes #2737

### CODE REVIEW

File: src/processor/operator/persistent/reader/csv/driver.cpp [hunk 1]
```diff
@@ -35,9 +35,13 @@ void ParsingDriver::addValue(
             stringFormat("Error in file {}, on line {}: expected {} values per row, but got more.",
                 reader->fileInfo->path, reader->getLineNumber(), reader->numColumns));
     }
-
-    function::CastString::copyStringToVector(
-        chunk.getValueVector(columnIdx).get(), rowNum, value, &reader->option);
+    try {
```
Comment (andyfengHKU) [inline src/processor/operator/persistent/reader/csv/driver.cpp:38]: Can u try to load comment.csv again after this PR.

I always heard that try catch has a performance issue even if the catch block is never triggered.

If the performance stays the same. The rest looks good to me.

**Review by andyfengHKU — APPROVED** [review]
