### PR TITLE
Fix duplicate quote char in JSON CASTING

### LINKED ISSUE #4462: Bug: CAST to json has duplicated quote char
### Kùzu version

v0.6.0

### What operating system are you using?

Ubuntu

### What happened?

`return cast ('{"duck": 42}' as json)`

results in

`""{\""duck\"": 42}""`

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by SterlingT3485**
# Description

The BUG happened because we don't parse string in our `jsonify` function, by adding a check to detect the type might be in the string in `jsonify` and use `stringToJson` , we can now handle this case.

Will be adding more test cases for JSON casting

Fixes #4462  

# Contributor agreement

- [ ] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/common/string_utils.cpp [hunk 1]
```diff
@@ -61,7 +61,8 @@ std::vector<std::string_view> StringUtils::smartSplit(std::string_view input, ch
                 result.push_back(input.substr(currentItem, i - currentItem));
                 currentItem = i + 1;
             }
-        } else if (c == '{' || c == '(' || c == '[' || c == '\"') {
+        } else if (c == '{' || c == '(' || c == '[' ||
+                   (c == '\"' && (stk.size() == 0u || stk.back() != '\"'))) {
```
Comment (acquamarin) [inline src/common/string_utils.cpp:65]: I would just write stk.size() == 0;

**Review by acquamarin — APPROVED** [review]

File: src/common/string_utils.cpp (hunk 1 above)
Comment (SterlingT3485) [reply src/common/string_utils.cpp]: changed to 0
