### PR TITLE
Fix 3652

### LINKED ISSUE #3652: Bug: Kuzu CLI hangs with `iri` property
### Kùzu version

v0.4.2

### What operating system are you using?

Fedora 39

### What happened?

```cypher
CREATE NODE TABLE V (id INT64, PRIMARY KEY(id));
CREATE REL TABLE E (FROM V TO V, iri STRING);
MATCH (v:V)-[e:E]->(v2:V) RETURN *;
```
Last statement will hang. Replacing `iri` by `p` works as usual.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by andyfengHKU**
# Description

The problem is that user use a reserved keyword as column name. This PR performs a check over column name in DDL.

Fixes #3652

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/binder/binder.cpp [hunk 1]
```diff
@@ -172,15 +172,36 @@ std::string Binder::getUniqueExpressionName(const std::string& name) {
...
-        return true;
-    }
-    if (normalizedName == StringUtils::getUpper(std::string(rdf::PID))) {
-        return true;
-    }
-    return false;
+    return reservedColumnNames.contains(normalizedName);
+}
+
+static std::unordered_set<std::string> reservedPropertyLookup = {
```
Comment (ray6080) [inline src/binder/binder.cpp:197]: What's the difference between `reservedPropertyLookup` and `reservedColumnNames`? Is the latter one used by ddl statements and the former one used by read clauses? I don't think the name is clear here. better rename it or add comments to explain it a bit more.

**Review by ray6080 — APPROVED** [review]
