### PR TITLE
Fix mismatched column IDs during insert and copy after drop and add columns

### LINKED ISSUE #4777: Bug: Failure during insert/copy after drop and add column in a table
### Kùzu version

master

### What operating system are you using?

MacOS

### What happened?

```cypher
CREATE NODE TABLE person(id INT64 PRIMARY KEY, name STRING);
CREATE (:person {id: 10, name: 'A'});
ALTER TABLE person DROP name;
ALTER TABLE person ADD age INT64;
CREATE (:person {id: 20, age: 20});
```
The last create statement fails after a DROP column and a ADD column statement.
Same when the last statement is COPY FROM.

The failure is due to that we didn't really remove a dropped column from storage before CHECKPOINT (this is due to that we need to maintain various versions of the table). Thus the column to be inserted / copied into are mismatched internally.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by ray6080**
# Description

Drop column can cause mismatched column IDs when inserting or copying into tables. The main reason is due to that we don't remove the dropped column immediately until checkpoint. The fix introduces column ids when appending into the table.

Fix #4777 and #4783

### CODE REVIEW

File: src/storage/store/rel_table_data.cpp [hunk 1]
```diff
@@ -283,7 +281,7 @@ const VersionRecordHandler* RelTableData::getVersionRecordHandler(CSRNodeGroupSc
     }
 }
 
-void RelTableData::rollbackGroupCollectionInsert(common::row_idx_t numRows_, bool isPersistent) {
+void RelTableData::rollbackGroupCollectionInsert(row_idx_t numRows_, bool isPersistent) {
```
Comment (andyfengHKU) [inline src/storage/store/rel_table_data.cpp:284]: Double check coverage here and l274

**Review by andyfengHKU — APPROVED** [review]
