### PR TITLE
tidy: add clang-tidy

### LINKED ISSUE #2152: Segfault in `getArrowSchema`
```
#include "kuzu.h"

int main() {
    kuzu_system_config conf;
    kuzu_database* db = kuzu_database_init("test", conf);
    kuzu_connection* conn = kuzu_connection_init(db);
    kuzu_query_result* result = kuzu_connection_query(conn, "LOAD FROM 'test.csv' RETURN *;");
    kuzu_query_result_get_arrow_schema(result);
}
```

This segfaults, because:

```
            for (auto j = 0u; i < numProperties; j++) {
                auto name = NodeVal::getPropertyName(value, j);
                auto val = NodeVal::getPropertyVal(value, j);
                columnTypeInfo->childrenTypesInfo.push_back(
                    DataTypeInfo::getInfoForDataType(*val->getDataType(), name));
            }
```

This loop, in `query_result.cpp`, is infinite, as diagnosed by `clang-tidy`. Specifically, we have a typo, we are using `i` instead of `j`.

### PR DESCRIPTION
**Pull request by Riolku**
clang-tidy is a static analyzer, and can find many different issues. So far I have integrated a few simple checks, and disabled the remaining ones. They will be enabled in future PRs.

Closes #2152. Ref #2148.

### CODE REVIEW

File: src/function/base_lower_upper_operation.cpp [hunk 1]
```diff
@@ -32,10 +36,16 @@ void BaseLowerUpperFunction::convertCase(char* result, uint32_t len, char* input
...
+                std::string funcName = toUpper ? "UPPER" : "LOWER";
+                throw RuntimeException(common::StringUtils::string_format(
+                    "Failed calling {}: Invalid UTF-8", funcName));
+            }
             int convertedCodepoint =
                 toUpper ? utf8proc_toupper(codepoint) : utf8proc_tolower(codepoint);
-            auto success = utf8proc_codepoint_to_utf8(convertedCodepoint, newSize, result);
-            assert(success);
+            bool success = utf8proc_codepoint_to_utf8(convertedCodepoint, newSize, result);
+            KU_ASSERT(success);
```
Comment (acquamarin) [inline src/function/base_lower_upper_operation.cpp:48]: We can probably remove the assertion here.

File: src/main/plan_printer.cpp [hunk 2]
```diff
@@ -150,6 +150,10 @@ void OpProfileTree::printOpProfileBoxUpperFrame(uint32_t rowIdx, std::ostringstr
     oss << std::endl;
 }
 
+static std::string dashed_line_account_for_index(uint32_t width, uint32_t indent) {
```
Comment (acquamarin) [inline src/main/plan_printer.cpp:153]: use camel case for function names.

Comment (Riolku) [reply src/main/plan_printer.cpp:153]: good news - clang-tidy has a configurable check for identifier casing!

File: src/storage/stats/node_table_statistics.cpp [hunk 3]
```diff
@@ -113,7 +113,7 @@ void NodeTableStatsAndDeletedIDs::setDeletedNodeOffsetsForMorsel(
         auto itr = deletedNodeOffsets.begin();
         sel_t nextDeletedNodeOffset = *itr - morselBeginOffset;
         uint64_t nextSelectedPosition = 0;
-        for (sel_t pos = 0; pos < nodeOffsetVector->state->getOriginalSize(); ++pos) {
+        for (size_t pos = 0; pos < nodeOffsetVector->state->getOriginalSize(); ++pos) {
```
Comment (andyfengHKU) [inline src/storage/stats/node_table_statistics.cpp:116]: auto

File: src/optimizer/agg_key_dependency_optimizer.cpp [hunk 4]
```diff
@@ -67,16 +67,17 @@ AggKeyDependencyOptimizer::resolveKeysAndDependentKeys(const binder::expression_
     for (auto& expression : keys) {
         if (expression->expressionType == PROPERTY) {
             auto propertyExpression = (binder::PropertyExpression*)expression.get();
-            if (propertyExpression->isPrimaryKey() || propertyExpression->isInternalID()) {
+            if (propertyExpression->isPrimaryKey() ||
```
Comment (andyfengHKU) [inline src/optimizer/agg_key_dependency_optimizer.cpp:70]: Does this imply we should try to collapse this if-else statement?

Comment (Riolku) [reply src/optimizer/agg_key_dependency_optimizer.cpp:70]: Uh, I don't understand the question. `clang-tidy` emits a warning here because branches 1 & 3 have identical bodies. However, rewriting this logic makes it just wrong, so I've instead told clang-tidy to ignore this check for this line.

File: src/include/common/system_message.h [hunk 5]
```diff
@@ -0,0 +1,16 @@
+#pragma once
+
+#include <cerrno>
+#include <string>
+#include <system_error>
+
+namespace kuzu {
+namespace common {
+inline std::string system_err_message(int code) {
```
Comment (ray6080) [inline src/include/common/system_message.h:9]: Is it intentional to use snake case for function name?

**Comment by ray6080** [comment]
Is there a summarized list of checks we plan to integrate later?

File: src/include/common/system_message.h (hunk 5 above)
Comment (Riolku) [reply src/include/common/system_message.h:9]: No, good catch.

**Comment by Riolku** [comment]
> Is there a summarized list of checks we plan to integrate later?

Not really, I plan to integrate everything except stuff I think is dumb or for which the check is poor quality.

For instance, I disabled bugprone-exception-escape because of the poor quality of the errors. I disabled bugprone namespace forward declarations because I dont see how this could be an issue, and we had some warnings from it and Arrow.

I disabled the widening multiplication becausr there are a lot of errors, and we need to fix that in its own PR.

**Comment by Riolku** [comment]
Note: we can't easily test returning `node` and getting the arrow schema of the result because we don't have good enough data type support for `getArrowSchema` and the nodes in tinysnb all have incompatible data types.

**Review by acquamarin — APPROVED** [review]
