### PR TITLE
Take null values into account for copy statistics

### LINKED ISSUE #3572: Incorrect statistics on relationship table.
### Kùzu version

master

### What happened?

When running `CALL storage_info('knows') RETURN *` on `tinysnb`. The min & max value on `date` column is incorrect. It reflects the statistics for initial copy but not for the second one.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by benjaminwinger**
I've added additional tests to the copy rel statistics test, and also fixed a typo in tinysnb ("temprature" -> "temperature").
I also added special handling for bools in `column.cpp:getMinMax` since it was treating bool data as uncompressed instead of bitpacked.

This also uncovered an issue with the list columns, where we're assuming its safe to read null lists, where in reality that's only the case if the size is 0. Unfortunately, compressing data with nulls may result in null values being non-zero after decompression due to frame of reference compression and, well, ignoring null values when determining the range used for compression.

Here I've just made the ListColumnChunk use a size of zero for any null offset, though it may be useful to remove null chunks for columns which don't need them like the list size and column.

Fixes #3572 (again)

### CODE REVIEW

File: src/storage/store/column_chunk.cpp [hunk 1]
```diff
@@ -403,67 +403,59 @@ bool ColumnChunk::sanityCheck() {
...
 ColumnChunkMetadata ColumnChunk::getMetadataToFlush() const {
     KU_ASSERT(numValues <= capacity);
-    StorageValue minValue = {}, maxValue = {};
+    std::optional<StorageValue> minValue, maxValue;
     if (capacity > 0) {
+        std::optional<NullMask> nullMask;
+        if (nullChunk) {
+            nullMask = nullChunk->getNullMask();
+        }
+        auto minmax_element = [&]<typename T>(std::span<T> data) {
```
Comment (ray6080) [inline src/storage/store/column_chunk.cpp:412]: Can we make this as a function instead of a lambda? The former is more readable to me 😅 .

File: src/storage/store/column_chunk.cpp [hunk 2]
```diff
@@ -403,67 +403,59 @@ bool ColumnChunk::sanityCheck() {
 
 ColumnChunkMetadata ColumnChunk::getMetadataToFlush() const {
     KU_ASSERT(numValues <= capacity);
-    StorageValue minValue = {}, maxValue = {};
+    std::optional<StorageValue> minValue, maxValue;
     if (capacity > 0) {
+        std::optional<NullMask> nullMask;
```
Comment (ray6080) [inline src/storage/store/column_chunk.cpp:408]: Are we able to merge the code of computing min/max here with the one (`getMinMax`) inside `Column`? I feel they duplicate the same logic though very minor variations.

**Review by ray6080 — APPROVED** [review]

File: src/storage/store/column_chunk.cpp (hunk 2 above)
Comment (benjaminwinger) [reply src/storage/store/column_chunk.cpp:407]: Yes, that's a good idea.
