### PR TITLE
Fix launch database using homedir

### LINKED ISSUE #3104: Opening a database from the home directory causes a segmentation fault
How to reproduce:
```py
import kuzu
db = kuzu.Database("~/tmpdatabase")
```
This produces a segmentation fault for me. I'm running on the master branch.

### PR DESCRIPTION
**Pull request by acquamarin**
closes #3104

### CODE REVIEW

File: src/main/database.cpp [hunk 1]
```diff
@@ -72,10 +73,13 @@ static void getLockFileFlagsAndType(bool readOnly, bool createNew, int& flags, F
 }
 
 Database::Database(std::string_view databasePath, SystemConfig systemConfig)
-    : databasePath{databasePath}, systemConfig{systemConfig} {
+    : systemConfig{systemConfig} {
     initLoggers();
     logger = LoggerUtils::getLogger(LoggerConstants::LoggerEnum::DATABASE);
     vfs = std::make_unique<VirtualFileSystem>();
+    auto clientContext = ClientContext(this);
```
Comment (andyfengHKU) [inline src/main/database.cpp:80]: comment why we are doing this.

**Review by andyfengHKU — APPROVED** [review]
