### PR TITLE
Fix syntax highlighting for quotes

### LINKED ISSUE #5686: Bug: incorrect syntax highlighting in shell
Image

I believe there should be no red highlighting.
It seems like parentheses inside string literals are not handled properly, and neither are single quote string literals containing an escaped single quote.

### PR DESCRIPTION
**Pull request by 05st**
It was skipping the `'` or `"` character which prevented the state from being set back to `STANDARD`.

Resolves #5686

### CODE REVIEW

File: tools/shell/linenoise.cpp [hunk 1]
```diff
@@ -1764,28 +1762,16 @@ void addErrorHighlighting(uint64_t render_start, uint64_t render_end,
...
-                }
+            if (c == '\'' && (i == 0 || l->buf[i - 1] != '\\')) {
+                // revert to standard scan state if not escaped quote
+                state = ScanState::STANDARD;
             }
             break;
         case ScanState::IN_DOUBLE_QUOTE:
             // double quote - all that will get us out is an unescaped quote
-            if (c == '"') {
-                if (i > 0 && l->buf[i - 1] == '\\') { // escaped quote
```
Comment (sdht0) [inline tools/shell/linenoise.cpp:1781]: What happens for the else case now, when the state is not reset?

**Review by sdht0 — APPROVED** [review]
Looks okay, although I haven't looked at the overall logic.

Can you explain in a comment the before and after behavior?

File: tools/shell/linenoise.cpp (hunk 1 above)
Comment (05st) [reply tools/shell/linenoise.cpp:1781]: Suppose the buffer looks like this: `\''`. Previously, when we were at the first `'` character, we incremented `i`. This resulted in skipping the next `'` character for the next iteration which was supposed to end the quote and set the state back to `STANDARD`.

In the else case, the character is part of the string (so either a non-quote character or an escaped quote). So we don't do anything.
