### PR TITLE
Issue 2385

### LINKED ISSUE #2385: Create non-string list of list with empty and non-empty list causes binder exception
Create list `[[23, 432], [], [NULL]]` fails `Binder exception: Cannot bind LIST_CREATION with parameter type INT64[] and STRING[]` since `NULL` is casted to String

### PR DESCRIPTION
**Pull request by andyfengHKU**
Fix #2385 and issue #2754.

This is done be assigning INT64 as default value to LIST_CREATION rather than STRING. Because INT64[] can be cast to STRING[] but not in the reverse direction.

Additionally, we now allow resolving a combined data type by ignoring empty list whose data type can be changed arbitrarily. E.g. `[[], ['a']]` should ignore the type of first entry and resolve type as STRING[][].

### CODE REVIEW

File: src/binder/expression/expression_util.cpp [hunk 1]
```diff
@@ -162,12 +164,126 @@ void ExpressionUtil::validateDataType(const Expression& expr,
...
+    }
+    switch (type.getLogicalTypeID()) {
+    case LogicalTypeID::LIST: {
+        return compatible(ListType::getChildType(type), ListType::getChildType(target));
+    }
+    case LogicalTypeID::ARRAY: {
+        return compatible(ArrayType::getChildType(type), ArrayType::getChildType(target));
+    }
+    case LogicalTypeID::STRUCT: {
+        if (StructType::getNumFields(type) != StructType::getNumFields(target)) {
```
Comment (acquamarin) [inline src/binder/expression/expression_util.cpp:187]: I would refactor this code as a function:
compatibleStruct()

File: src/binder/expression/expression_util.cpp [hunk 2]
```diff
@@ -162,12 +164,126 @@ void ExpressionUtil::validateDataType(const Expression& expr,
...
+static bool compatible(const Value& value, const LogicalType& targetType) {
+    if (value.isNull()) { // Value is null. We can safely change its type.
+        return true;
+    }
+    if (value.getDataType()->getLogicalTypeID() != targetType.getLogicalTypeID()) {
+        return false;
+    }
+    switch (value.getDataType()->getLogicalTypeID()) {
+    case LogicalTypeID::LIST: {
+        if (!value.hasNoneNullChildren()) { // Empty list free to change.
```
Comment (acquamarin) [inline src/binder/expression/expression_util.cpp:222]: Ditto, better refactor as a function

**Review by acquamarin — APPROVED** [review]
