### PR TITLE
Fix match after fts query

### LINKED ISSUE #4930: Bug: FTS with traversal results in RuntimeError: vector::_M_default_append
### Kùzu version

v0.8.0

### What operating system are you using?

Ubuntu 22.04.4 LTS

### What happened?

Using the python client I can create and query an FTS index successfully like this:
```
CALL QUERY_FTS_INDEX('Technology_or_Tool','full_text_search_index','emulate')
WITH node as n ORDER BY score DESC LIMIT 5
MATCH (n)
RETURN n.*;
```

However, when I attempt to traverse the graph from there I get a runtime error "vector::_M_default_append"
```
CALL QUERY_FTS_INDEX(
    'Technology_or_Tool',
    'full_text_search_index',
    'emulate'
) 
WITH node.e_key as doc_key, score
ORDER BY score DESC LIMIT 5
MATCH (a:Technology_or_Tool {e_key: doc_key})-[]->(b)
RETURN a.name, 
       b.name;
```
Results in:
```
[/usr/local/lib/python3.11/dist-packages/kuzu/connection.py](https://localhost:8080/#) in execute(self, query, parameters)
    128 
    129         if len(parameters) == 0:
--> 130             _query_result = self._connection.query(query)
    131         else:
    132             prepared_statement = self.prepare(query) if isinstance(query, str) else query

RuntimeError: vector::_M_default_append
```

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by acquamarin**
fixes #4930 
We should set `useInternalTable` to false after binding queryFTS.

### CODE REVIEW

File: extension/fts/src/function/query_fts_index.cpp [hunk 1]
```diff
@@ -339,6 +339,7 @@ void QueryFTSAlgorithm::bind(const GDSBindInput& input, main::ClientContext& con
     auto graphEntry = graph::GraphEntry({termsEntry, docsEntry}, {appearsInEntry});
     bindData = std::make_unique<QueryFTSBindData>(std::move(graphEntry), nodeOutput,
         std::move(query), *ftsIndexEntry, QueryFTSConfig{input.optionalParams});
+    context.setUseInternalCatalogEntry(false /* useInternalCatalogEntry */);
```
Comment (andyfengHKU) [inline extension/fts/src/function/query_fts_index.cpp:342]: Now that I see this. I would double check CreateFTS and other places, e.g. create index & vector index. And make sure we always set to false afterwards.

**Review by andyfengHKU — APPROVED** [review]

File: extension/fts/src/function/query_fts_index.cpp (hunk 1 above)
Comment (acquamarin) [reply extension/fts/src/function/query_fts_index.cpp:342]: I don't think we support match query after standalone call function:
```
CALL CREATE_FTS_INDEX('doc', 'docIdx4', ['content', 'name']) match (n) return n
```
