### PR TITLE
export-import: implement parallel=false flag on export to fix import function

### LINKED ISSUE #5727: Bug: Import does not support (parallel=false)
### Kuzu version

0.10.0 and Master

### What operating system are you using?

MacOS

### What happened?

```
tanvirgahunia@Tanvirs-MacBook-Pro kuzu % ./../exec --version
exec(63491,0x20dcf9f00) malloc: nano zone abandoned due to inability to reserve vm space.
Kuzu 0.10.0
tanvirgahunia@Tanvirs-MacBook-Pro kuzu % ./../exec
exec(63492,0x20dcf9f00) malloc: nano zone abandoned due to inability to reserve vm space.
Opening the database under in-memory mode.
Enter ":help" for usage hints.
kuzu> CREATE NODE TABLE basic(A STRING, PRIMARY KEY(A));
┌───────────────────────────────┐
│ result                        │
│ STRING                        │
├───────────────────────────────┤
│ Table basic has been created. │
└───────────────────────────────┘
(1 tuple)
(1 column)
Time: 9.74ms (compiling), 2.72ms (executing)
kuzu> CREATE NODE TABLE `mixed-newlines`(A STRING, B STRING, PRIMARY KEY(A));
┌────────────────────────────────────────┐
│ result                                 │
│ STRING                                 │
├────────────────────────────────────────┤
│ Table mixed-newlines has been created. │
└────────────────────────────────────────┘
(1 tuple)
(1 column)
Time: 3.42ms (compiling), 5.59ms (executing)
kuzu> COPY basic FROM "dataset/csv-multiline-quote-tests/basic.csv" (PARALLEL=FALSE);
┌───────────────────────────────────────────────┐
│ result                                        │
│ STRING                                        │
├───────────────────────────────────────────────┤
│ 1 tuples have been copied to the basic table. │
└───────────────────────────────────────────────┘
(1 tuple)
(1 column)
Time: 19.64ms (compiling), 23.38ms (executing)
kuzu> COPY `mixed-newlines` FROM "dataset/csv-multiline-quote-tests/mixed-newlines.csv" (PARALLEL=FALSE);
┌────────────────────────────────────────────────────────┐
│ result                                                 │
│ STRING                                                 │
├────────────────────────────────────────────────────────┤
│ 1 tuples have been copied to the mixed-newlines table. │
└────────────────────────────────────────────────────────┘
(1 tuple)
(1 column)
Time: 4.08ms (compiling), 34.73ms (executing)
kuzu> export database './tmp' (format="csv", header=true, PARALLEL=FALSE);
┌─────────────────────────────────┐
│ result                          │
│ STRING                          │
├─────────────────────────────────┤
│ Exported database successfully. │
└─────────────────────────────────┘
(1 tuple)
(1 column)
Time: 64.27ms (compiling), 3.13ms (executing)
kuzu> :quit
tanvirgahunia@Tanvirs-MacBook-Pro kuzu % ./build/debug/tools/shell/kuzu --version
kuzu(63519,0x20dcf9f00) malloc: nano zone abandoned due to inability to reserve vm space.
Kuzu 0.10.0.6
tanvirgahunia@Tanvirs-MacBook-Pro kuzu % ./build/debug/tools/shell/kuzu
kuzu(63520,0x20dcf9f00) malloc: nano zone abandoned due to inability to reserve vm space.
Opening the database under in-memory mode.
Enter ":help" for usage hints.
kuzu> CALL threads=1;
(0 tuples)
(0 columns)
Time: 45.04ms (compiling), 0.28ms (executing)
kuzu> import database './tmp';
Error: Runtime exception: Import database failed: Copy exception: Error in file ./tmp/basic.csv on line 2: Quoted newlines are not supported in parallel CSV reader. Please specify PARALLEL=FALSE in the options. Line/record containing the error: '"abc'
kuzu> import database './tmp';
Error: Runtime exception: Import database failed: Binder exception: basic already exists in catalog.
kuzu>
```

### Are there known steps to reproduce?

_No response_

### LINKED ISSUE #5761: (export and import): quotes not preserved on multiline strings
### Kuzu version

0.11.0

### What operating system are you using?

MacOS

### What happened?

Found while implementing the `parallel=false` flag for `IMPORT DATABASE`

See reproduction below. The quotes around `abc def` are not preserved in export. 

```
tanvirgahunia@Tanvirs-MacBook-Pro kuzu % ./build/debug/tools/shell/kuzu
Opening the database under in-memory mode.
Enter ":help" for usage hints.
kuzu> CREATE NODE TABLE `mixed-newlines`(A STRING, B STRING, PRIMARY KEY(A));
┌────────────────────────────────────────┐
│ result                                 │
│ STRING                                 │
├────────────────────────────────────────┤
│ Table mixed-newlines has been created. │
└────────────────────────────────────────┘
(1 tuple)
(1 column)
Time: 11.89ms (compiling), 7.41ms (executing)
kuzu> COPY `mixed-newlines` FROM "dataset/csv-multiline-quote-tests/mixed-newlines.csv" (PARALLEL=FALSE);
┌────────────────────────────────────────────────────────┐
│ result                                                 │
│ STRING                                                 │
├────────────────────────────────────────────────────────┤
│ 1 tuples have been copied to the mixed-newlines table. │
└────────────────────────────────────────────────────────┘
(1 tuple)
(1 column)
Time: 12.23ms (compiling), 12.77ms (executing)
kuzu> export database 'tmp' (format='csv');
┌─────────────────────────────────┐
│ result                          │
│ STRING                          │
├─────────────────────────────────┤
│ Exported database successfully. │
└─────────────────────────────────┘
(1 tuple)
(1 column)
Time: 38.99ms (compiling), 2.07ms (executing)
kuzu> :quit
tanvirgahunia@Tanvirs-MacBook-Pro kuzu % diff tmp/mixed-newlines.csv dataset/csv-multiline-quote-tests/mixed-newlines.csv
1,2c1,2
< abc
< def,"ghi
---
> "abc
> def","ghi
tanvirgahunia@Tanvirs-MacBook-Pro kuzu %
```

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by tgahunia05**
# Description
Fixes #5727 
Fixes #5761 

Summary of Changes: 
Reorders export order of operations such that .cypher files are created after data has been exported. During export, if we find that the db cannot be imported using a parallel csv reader (there is a multiline string in the csv) we propagate this information to the copy.cypher file (add parallel=false flag to copy statements). 

We also treat carriage return (`\r`) as a newline character on export to be consistent with import.

# Contributor agreement

- [X] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

**Review by acquamarin — COMMENTED** [review]
Instead of adding options to the import function, the better way to implement this is to export (parallel=false) option to the `copy.cypher` file.
When we export a table as csv which requires to import in single thread, we export the csv and add the `(parallel=false)` option to the `copy.cypher` file.
It is confusing for users to know when to add the `parallel=false` option to the import command.

**Review by acquamarin — CHANGES_REQUESTED** [review]

File: src/processor/operator/simple/export_db.cpp [hunk 1]
```diff
@@ -42,8 +42,9 @@ std::string ExportDBPrintInfo::toString() const {
 
 void ExportDB::initGlobalStateInternal(ExecutionContext* context) {
     const auto vfs = context->clientContext->getVFSUnsafe();
-    KU_ASSERT(!vfs->fileOrPathExists(boundFileInfo.filePaths[0], context->clientContext));
-    vfs->createDir(boundFileInfo.filePaths[0]);
+    if (!vfs->fileOrPathExists(boundFileInfo.filePaths[0], context->clientContext)) {
```
[the remark this answers is not in the document]
Comment (tgahunia05) [reply src/processor/operator/simple/export_db.cpp:45]: This part of the code was never responsible for throwing an error (thus the KU_ASSERT and not throw RuntimeException).

See `std::unique_ptr<PhysicalOperator> PlanMapper::mapExportDatabase`

It checks if the directory already exists and throws if it does.

This part of the code is responsible for creating the directory. In the past, this was okay, but if we want to write copy.cypher first this directory creation must happen earlier. Right now the export fcns create the directory. After some more thought, I am going to move it to 

`std::unique_ptr<PhysicalOperator> PlanMapper::mapExportDatabase` so that checking if the directory exists and creating the directory are events that are closer together.

File: src/include/processor/operator/simple/export_db.h [hunk 2]
```diff
@@ -30,22 +30,29 @@ class ExportDB final : public SimpleSink {
...
+    }
+    auto setParallelReaderFalse() {
+        auto parallelFalse = [this]() { *canUseParallelCSVReader = false; };
+        return parallelFalse;
     }
 
 private:
     common::FileScanInfo boundFileInfo;
     bool schemaOnly;
+    std::shared_ptr<bool> canUseParallelCSVReader;
```
[the remark this answers is not in the document]
Comment (tgahunia05) [reply src/include/processor/operator/simple/export_db.h]: Storing a reference does not seem like the right thing to do here. 

Taken from e2e_test_binary_demo~demo_db.DemoDBTest.
Consider 
`COPY (MATCH (u:User) RETURN u.*) TO 'user.csv' (header=true);`

This ends up calling the `exportCSV` function. We are not generating a copy.cypher file here, therefore there would be no parallelFlag to change when doing the check for a multiline string. The aforementioned test fails. 

/Users/runner/Developer/actions-runner/_work/kuzu/kuzu/test/test_runner/test_runner.cpp:116: Failure
Value of: queryResult->isSuccess()
  Actual: false
Expected: true
EXPECT OK BUT GOT ERROR: Assertion failed in file "/Users/runner/Developer/actions-runner/_work/kuzu/kuzu/src/function/export/export_csv_function.cpp" on line 118: parallelFlag != nullptr


I instead propose storing a ptr to the boolean, and changing the flag to false if the ptr is not nullptr and we encounter a multiline string.

File: extension/json/src/functions/export_functions/json_export.cpp [hunk 3]
```diff
@@ -32,7 +32,8 @@ struct ExportJSONSharedState : public ExportFuncSharedState {
     std::unique_ptr<FileInfo> fileInfo;
     std::vector<std::string> jsonValues;
 
-    void init(main::ClientContext& context, const ExportFuncBindData& bindData) override {
+    void init(main::ClientContext& context, const ExportFuncBindData& bindData,
+        const std::shared_ptr<std::atomic<bool>>& /*parallelFlag*/) override {
```
Comment (acquamarin) [inline extension/json/src/functions/export_functions/json_export.cpp:36]: you don't have to wrap shared_ptr with reference. just pass std::atomic<bool>& there.

File: extension/json/src/functions/export_functions/json_export.cpp [hunk 4]
```diff
@@ -47,8 +48,8 @@ static std::unique_ptr<ExportFuncBindData> bindFunc(ExportFuncBindInput& bindInp
 }
 
 static void initSharedState(ExportFuncSharedState& sharedState, main::ClientContext& context,
-    const ExportFuncBindData& bindData) {
-    sharedState.init(context, bindData);
+    const ExportFuncBindData& bindData, const std::shared_ptr<std::atomic<bool>>& parallelFlag) {
```
Comment (acquamarin) [inline extension/json/src/functions/export_functions/json_export.cpp:51]: Ditto, std::atomic<bool> should be fine.

File: src/include/processor/operator/persistent/copy_to.h [hunk 5]
```diff
@@ -53,9 +55,10 @@ class CopyTo final : public Sink {
 public:
     CopyTo(CopyToInfo info, std::shared_ptr<function::ExportFuncSharedState> sharedState,
         std::unique_ptr<PhysicalOperator> child, uint32_t id,
-        std::unique_ptr<OPPrintInfo> printInfo)
+        std::unique_ptr<OPPrintInfo> printInfo,
+        std::shared_ptr<std::atomic<bool>> parallelFlag = nullptr)
         : Sink{type_, std::move(child), id, std::move(printInfo)}, info{std::move(info)},
-          sharedState{std::move(sharedState)} {}
+          sharedState{std::move(sharedState)}, parallelFlag{std::move(parallelFlag)} {}
```
Comment (acquamarin) [inline src/include/processor/operator/persistent/copy_to.h:61]: You can move parallelFlag to sharedState, and remove the shared_ptr<>

File: src/include/processor/operator/persistent/copy_to.h [hunk 6]
```diff
@@ -65,15 +68,20 @@ class CopyTo final : public Sink {
 
     void executeInternal(ExecutionContext* context) override;
 
+    void setParallel(const std::shared_ptr<std::atomic<bool>>& parallelFlag) {
```
Comment (acquamarin) [inline src/include/processor/operator/persistent/copy_to.h:71]: Ditto, wrap parallelFlag in the sharedState, and set it in the initSharedState

File: src/processor/map/map_simple.cpp [hunk 7]
```diff
@@ -57,6 +58,16 @@ std::unique_ptr<PhysicalOperator> PlanMapper::mapDetachDatabase(
         getOperatorID(), std::move(printInfo));
 }
 
+void mapExportDatabaseHelper(PhysicalOperator* physicalOperator,
+    const std::shared_ptr<std::atomic<bool>>& parallelFlag) {
+    for (unsigned int i{}; i < physicalOperator->getNumChildren(); ++i) {
```
Comment (acquamarin) [inline src/processor/map/map_simple.cpp:63]: Our convension for loop is  `for(auto i = 0u; i< xxx; i++)`

File: src/processor/map/map_simple.cpp [hunk 8]
```diff
@@ -57,6 +58,16 @@ std::unique_ptr<PhysicalOperator> PlanMapper::mapDetachDatabase(
...
+        if (physicalOperator->getChild(i)->getOperatorType() == PhysicalOperatorType::COPY_TO) {
```
Comment (acquamarin) [inline src/processor/map/map_simple.cpp:64]: Except the first child, all other children must be `COPY_TO`, so you can assume all child operators starting from idx1 should be `copy_to`.

File: src/include/processor/operator/simple/export_db.h [hunk 9]
```diff
@@ -30,22 +30,27 @@ class ExportDB final : public SimpleSink {
 public:
     ExportDB(common::FileScanInfo boundFileInfo, bool schemaOnly,
         std::shared_ptr<FactorizedTable> messageTable, physical_op_id id,
-        std::unique_ptr<OPPrintInfo> printInfo)
+        std::unique_ptr<OPPrintInfo> printInfo,
+        const std::shared_ptr<std::atomic<bool>>& canUseParallelCSVReader =
```
Comment (acquamarin) [inline src/include/processor/operator/simple/export_db.h:34]: Move `canUseParallelCSVReader` to the sharedState.

File: src/processor/map/map_simple.cpp [hunk 10]
```diff
@@ -67,16 +78,22 @@ std::unique_ptr<PhysicalOperator> PlanMapper::mapExportDatabase(
...
         FactorizedTableUtils::getSingleStringColumnFTable(clientContext->getMemoryManager());
     auto exportDB = std::make_unique<ExportDB>(boundFileInfo->copy(),
         exportDatabase->isSchemaOnly(), messageTable, getOperatorID(), std::move(printInfo));
     auto sink = std::make_unique<DummySimpleSink>(messageTable, getOperatorID());
+    sink->addChild(std::move(exportDB));
     for (auto child : exportDatabase->getChildren()) {
         sink->addChild(mapOperator(child.get()));
     }
-    sink->addChild(std::move(exportDB));
+    if (boundFileInfo->fileTypeInfo.fileType == common::FileType::CSV) {
```
Comment (acquamarin) [inline src/processor/map/map_simple.cpp:92]: You don't have to check whether this is csv or not, you can always init the parallelFlag in the exportdb sharedState..

File: extension/json/src/functions/export_functions/json_export.cpp (hunk 4 above)
Comment (tgahunia05) [reply extension/json/src/functions/export_functions/json_export.cpp]: Marking as resolved as per our discussion.

File: src/include/processor/operator/persistent/copy_to.h (hunk 6 above)
Comment (tgahunia05) [reply src/include/processor/operator/persistent/copy_to.h]: Marking as resolved as per our discussion.

File: src/include/processor/operator/simple/export_db.h (hunk 9 above)
Comment (tgahunia05) [reply src/include/processor/operator/simple/export_db.h]: Marking as resolved as per our discussion. I have tried to do this with our map.

File: src/include/processor/operator/persistent/copy_to.h (hunk 5 above)
Comment (tgahunia05) [reply src/include/processor/operator/persistent/copy_to.h]: This has been done.

File: src/processor/operator/simple/export_db.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (tgahunia05) [reply src/processor/operator/simple/export_db.cpp]: Marking as resolved, this directory is create in `PlanMapper::mapExportDatabase`

File: src/include/common/copier_config/csv_reader_config.h [hunk 11]
```diff
@@ -46,8 +46,11 @@ struct CSVOption {
     EXPLICIT_COPY_DEFAULT_MOVE(CSVOption);
 
     // TODO: COPY FROM and COPY TO should support transform special options, like '\'.
-    std::unordered_map<std::string, std::string> toOptionsMap() const {
+    std::unordered_map<std::string, std::string> toOptionsMap(const bool& parallel) const {
         std::unordered_map<std::string, std::string> result;
+        if (!parallel) {
```
[the remark this answers is not in the document]
Comment (tgahunia05) [reply src/include/common/copier_config/csv_reader_config.h:51]: If the parallel argument is not specified the default is true. But sure, I can be more explicit and specify parallel=true.

File: src/function/export/export_csv_function.cpp [hunk 12]
```diff
@@ -46,13 +46,20 @@ static std::string addEscapes(char toEscape, char escape, const std::string& val
...
 
 static bool requireQuotes(const ExportCSVBindData& exportCSVBindData, const uint8_t* str,
-    uint64_t len) {
+    uint64_t len, std::atomic<bool>& parallelFlag) {
     // Check if the string is equal to the null string.
     if (len == strlen(ExportCSVConstants::DEFAULT_NULL_STR) &&
         memcmp(str, ExportCSVConstants::DEFAULT_NULL_STR, len) == 0) {
         return true;
     }
+    static constexpr const char* NEWLINE = "\n\r";
```
[the remark this answers is not in the document]
Comment (tgahunia05) [reply src/function/export/export_csv_function.cpp]: Yes. Although this constant is not just used in conditionals, it is also the same constant that is used when we need to write a newline to a file. 

Ex
```
bufferedSerializer.writeBufferData(ExportCSVConstants::DEFAULT_CSV_NEWLINE);
```


That code would need to be changed a bit.
