### PR TITLE
Fix explain export database statement

### LINKED ISSUE #3786: Bug: Using explain for export database ran the query
### Kùzu version

Master

### What happened?

I used explain to print the physical plan for my export database query and the query executed instead of just printing the plan.

### Are there known steps to reproduce?

I used this query `explain EXPORT DATABASE 'testingExport' (format="csv", header=true);`

The database has the User table from the Kuzu Docs

### PR DESCRIPTION
**Pull request by acquamarin**
# Description

This PR fixes explain export database statement.

Fixes #3786

### CODE REVIEW

File: src/include/function/export/export_function.h [hunk 1]
```diff
@@ -54,8 +58,9 @@ using bind_t =
     std::function<std::unique_ptr<ExportFuncBindData>(function::ExportFuncBindInput& bindInput)>;
 using init_local_t = std::function<std::unique_ptr<ExportFuncLocalState>(main::ClientContext&,
     const ExportFuncBindData&, std::vector<bool>)>;
-using init_shared_t = std::function<std::shared_ptr<ExportFuncSharedState>(main::ClientContext&,
-    ExportFuncBindData&)>;
+using create_shared_t = std::function<std::shared_ptr<ExportFuncSharedState>()>;
```
Comment (andyfengHKU) [inline src/include/function/export/export_function.h:61]: These type defines are globally visible. Just like we did for scalar_func_exec_t, better rename as export_func_xxx_t

File: src/processor/map/create_factorized_table_scan.cpp [hunk 2]
```diff
@@ -83,8 +93,12 @@ std::unique_ptr<PhysicalOperator> PlanMapper::createFTableScanAligned(
     for (auto i = 0u; i < exprs.size(); ++i) {
         colIndices.push_back(i);
     }
+    physical_op_vector_t children;
+    if (child != nullptr) {
```
Comment (andyfengHKU) [inline src/processor/map/create_factorized_table_scan.cpp:97]: if now ResultCollector can have multiple children, then its child should never be a nullptr. The previous nullptr was for EmptyResultCollector because we force ResultCollector to have exactly one child. Now EmptyResultCollector can just have an empty children vector.

File: src/function/export/export_parquet_function.cpp [hunk 3]
```diff
@@ -115,8 +121,9 @@ static void finalizeFunc(ExportFuncSharedState& sharedState) {
 function_set ExportParquetFunction::getFunctionSet() {
     function_set functionSet;
     auto exportFunc = std::make_unique<ExportFunction>(name);
-    exportFunc->initLocal = initLocalState;
-    exportFunc->initShared = initSharedState;
+    exportFunc->initLocalState = initLocalStateFunc;
+    exportFunc->createSharedState = createSharedStateFunc;
+    exportFunc->initSharedState = initSharedStateFunc;
```
Comment (andyfengHKU) [inline src/function/export/export_parquet_function.cpp:126]: I thought the normal design is to merge  createSharedState inside initSharedState just like the previous design. I believe we did this in multiple places not just for export

File: src/include/processor/operator/table_function_call.h [hunk 4]
```diff
@@ -96,10 +96,9 @@ class TableFunctionCall : public PhysicalOperator {
         : PhysicalOperator{type_, id, std::move(printInfo)}, info{std::move(info)},
           sharedState{std::move(sharedState)} {}
     TableFunctionCall(TableFunctionCallInfo info,
-        std::shared_ptr<TableFunctionCallSharedState> sharedState,
-        std::unique_ptr<PhysicalOperator> child, uint32_t id,
-        std::unique_ptr<OPPrintInfo> printInfo)
-        : PhysicalOperator{type_, std::move(child), id, std::move(printInfo)},
+        std::shared_ptr<TableFunctionCallSharedState> sharedState, physical_op_vector_t children,
```
Comment (andyfengHKU) [inline src/include/processor/operator/table_function_call.h:99]: Comment under what case TableFunctionCall needs multiple children

**Review by andyfengHKU — APPROVED** [review]
