### PR TITLE
Populate warning data for batch insert warnings with JSON source + populate line number for JSON scan errors

### LINKED ISSUE #4262: Feature: Report error line number when error occurs in the json reader.
### API

Python

### Description

To improve usability of the json reader, we should consider including the error line number when an exception occurs when reading json.
For example: 
Error message should look like:
```
Malformed JSON in file xxxx, at byte xxx in line xxxx
```
This could help users debugging.

### PR DESCRIPTION
**Pull request by royi-luo**
# Description
Batch insert warnings (e.g. duplicate PK, index lookup failure) from JSON source now have warning info (e.g. line number, file path) populated in the warning table.

As part of this change, the column `skipped_line` in the warning table have been renamed to `skipped_line_or_record` as for JSON we report the record that causes the error (which can span multiple lines, or only part of a line). The new warning table will look something like (if parsed from a JSON file):
```
┌──────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────┬─────────────┬────────────────────────┐
│ query_id │ message                                                                                                   │ file_path                               │ line_number │ skipped_line_or_record │
│ UINT64   │ STRING                                                                                                    │ STRING                                  │ UINT64      │ STRING                 │
├──────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────┼─────────────┼────────────────────────┤
│ 2        │ Found duplicated primary key value 1, which violates the uniqueness constraint of the primary key column. │ /home/kuzu/test/csv/dataset-json.json   │ 9200001     │ {"ID": 1, "age": 2}    │
│ 2        │ Found duplicated primary key value 1, which violates the uniqueness constraint of the primary key column. │ /home/kuzu/test/csv/dataset-json.json   │ 9000001     │ {"ID": 1, "age": 2}    │
│ 2        │ Found duplicated primary key value 1, which violates the uniqueness constraint of the primary key column. │ /home/kuzu/test/csv/dataset-json.json   │ 9100001     │ {"ID": 1, "age": 2}    │
└──────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────┴─────────────┴────────────────────────┘
```
JSON parsing messages are also updated to include line number + the reconstructed skipped line, something like `Copy exception: Error in file ${KUZU_ROOT_DIRECTORY}/dataset/json-error/structured.json on line 3: Malformed JSON: unexpected character, expected a valid JSON value. Line/record containing the error: '{"c":}...'`.

Most of the changes in this PR are refactorings to support the above changes.

**Sanity benchmarks are [here](https://github.com/kuzudb/kuzu/pull/4294#issuecomment-2374377609)**

Fixes #4262

# Contributor agreement

- [ ] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/include/common/data_chunk/data_chunk.h [hunk 1]
```diff
@@ -33,7 +33,7 @@ class DataChunk {
 
     inline uint32_t getNumValueVectors() const { return valueVectors.size(); }
 
-    inline std::shared_ptr<ValueVector> getValueVector(uint64_t valueVectorPos) {
+    inline const std::shared_ptr<ValueVector>& getValueVector(uint64_t valueVectorPos) const {
```
Comment (royi-luo) [inline src/include/common/data_chunk/data_chunk.h:36]: Changed this function to return a reference to the `std::shared_ptr` to avoid triggering the reference counting logic, I looked through the uses of this function and I don't think any of them do anything with the `std::shared_ptr` object. When parsing from a single column with `IGNORE_ERRORS=true` (which calls `getValueVector()` 6 times per value which is the worst case) this speeds up the overall copy by 5-10%.

File: src/include/common/utils.h [hunk 2]
```diff
@@ -54,5 +54,24 @@ constexpr To safeIntegerConversion(From val) {
...
+
+template<typename Func, typename... Types, size_t... indices>
+void paramPackFuncHelper(const Func& func, std::index_sequence<indices...>, Types&&... values) {
+    ((func(indices, values)), ...);
+}
+
+template<typename Func, typename... Types>
+void paramPackFunc(const Func& func, Types&&... values) {
+    paramPackFuncHelper(func, std::index_sequence_for<Types...>(), std::forward<Types>(values)...);
+}
```
Comment (royi-luo) [inline src/include/common/utils.h:74]: Move these to a new/different header so that we're not pulling `utils.h` and `numeric_utils.h` into almost every file

File: src/include/processor/warning_context.h [hunk 3]
```diff
@@ -1,105 +1,60 @@
...
-    bool operator<(const CSVError& o) const;
-};
-
-struct PopulatedCSVError {
-    std::string message;
-    std::string filePath;
-    std::string skippedLine;
-    uint64_t lineNumber;
-};
-
```
Comment (royi-luo) [inline src/include/processor/warning_context.h:66]: Moved these structs to `copy_from_error.h`

File: extension/json/src/reader/buffered_json_reader.cpp [hunk 4]
```diff
@@ -40,6 +40,21 @@ BufferedJsonReader::BufferedJsonReader(main::ClientContext& context, std::string
...
+    std::lock_guard<std::mutex> lockGuard{lock};
+
+    std::string ret;
+    ret.resize(endPosition - startPosition);
+
+    bool finishedFile = false;
+    fileHandle->readAtPosition(reinterpret_cast<uint8_t*>(ret.data()), ret.size(), startPosition,
+        finishedFile);
+
+    return StringUtils::ltrimNewlines(StringUtils::rtrimNewlines(ret));
```
Comment (royi-luo) [inline extension/json/src/reader/buffered_json_reader.cpp:55]: Our test runner and shell both don't deal well outputting with multiline values (which JSON records can be). Does anyone have suggestions on how to handle this? For now I'm thinking of just removing newlines from the `skipped_line_or_record` entries

File: extension/json/src/functions/table_functions/json_scan.cpp [hunk 5]
```diff
@@ -245,12 +312,26 @@ static uint8_t* nextJson(uint8_t* ptr, uint64_t size) {
...
+    const std::string& extra) const {
+    currentReader->throwParseError(err, completedParsingObject,
+        getWarningData(getFileOffset(), getFileOffset() + err.pos + 1), errorHandler.get(), extra);
+}
+
+void JSONScanLocalState::parseJson(uint8_t* jsonStart, uint64_t size, uint64_t remaining,
+    const std::optional<std::vector<ValueVector*>>& warningDataVectors) {
     yyjson_doc* doc = nullptr;
     yyjson_read_err err;
     doc = JSONCommon::readDocumentUnsafe(jsonStart, remaining, JSONCommon::READ_INSITU_FLAG, &err);
```
Comment (royi-luo) [inline extension/json/src/functions/table_functions/json_scan.cpp:332]: I'm pretty sure this leaks memory because we never free the `doc`. I'll fix this in a separate PR.

**Comment by royi-luo** [comment]
Some quick benchmarks, since there is quite a bit of refactoring I tested on multiple datasets to check for performance regressions. Note that due to some additional optimizations for CSV parsing results may be better than on master, although there is some additional copying overhead from `WarningSourceData` storing type information for each value:

## Dataset
Schema:
```
CREATE NODE TABLE person(ID UINT32, PRIMARY KEY(ID));
CREATE REL TABLE knows(FROM person TO person, MANY_MANY);
```
Details: 10M nodes in `person`, 10M rels in `knows`

## Duplicate PK Errors (CSV)

Query: `COPY person FROM "/home/kuzu/test/dataset/many-ok-pk.csv"(IGNORE_ERRORS={value});`

### Results
Branch|`IGNORE_ERRORS`|Error %|Copy Time (master)|Copy Time (new)
----|----|----|----|----
new|false|0%|515ms|575ms
new|true|0%|708ms|742ms
new|true|1%|852ms|893ms
new|true|10%|1072ms|1210ms
master|true|100%|4701ms|4944ms

## Index Lookup Errors (CSV)

Copy query: `COPY knows FROM "/home/kuzu/test/dataset/missing-pk-rels.csv"(IGNORE_ERRORS={value});`

### Results
Branch|`IGNORE_ERRORS`|Error %|Copy Time (master)|Copy Time (new)
----|----|----|----|----
new|false|0%|1546ms|1629ms
new|true|0%|2329ms|2352ms
new|true|10%|2256ms|2184ms
new|true|100%|1381ms|1268ms

## Duplicate PK Errors (JSON)

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 5 above)
Comment (royi-luo) [reply extension/json/src/functions/table_functions/json_scan.cpp:332]: Ended up fixing it here anyways

Comment (royi-luo) [reply extension/json/src/functions/table_functions/json_scan.cpp:331]: Opened PR [here](https://github.com/kuzudb/kuzu/pull/4302)

File: extension/json/src/functions/table_functions/json_scan.cpp [hunk 6]
```diff
@@ -380,11 +482,15 @@ bool JSONScanLocalState::readNextBuffer() {
 
     if (currentReader && currentBufferHandle) {
         if (--currentBufferHandle->numReaders == 0) {
```
Comment (royi-luo) [inline extension/json/src/functions/table_functions/json_scan.cpp:484]: @acquamarin is this operation thread-safe or should `numReaders` (and the `lineOrObjectCountInBuffer` I added) be atomic?

File: extension/json/src/reader/buffered_json_reader.cpp [hunk 7]
```diff
@@ -49,12 +64,12 @@ std::unique_ptr<storage::MemoryBuffer> BufferedJsonReader::removeBuffer(
     return result;
 }
 
-void BufferedJsonReader::throwParseError(yyjson_read_err& err, const std::string& extra) const {
-    auto unit = options.format == JsonScanFormat::NEWLINE_DELIMITED ? "line" : "record/value";
-    // TODO(Ziyi): report error line number.
-    throw common::RuntimeException{
-        common::stringFormat("Malformed JSON in file \"{}\", at byte {} in {}: {}. {}", fileName,
-            err.pos + 1, unit, err.msg, extra)};
```
Comment (royi-luo) [inline extension/json/src/reader/buffered_json_reader.cpp:57]: I removed the byte offset from the error message since I think having the record + reconstructed record should be sufficient

File: extension/json/src/functions/table_functions/json_scan.cpp [hunk 8]
```diff
@@ -21,6 +23,24 @@ using namespace kuzu::common;
 
 struct JsonScanBindData;
 
+static constexpr idx_t JSON_SCAN_FILE_IDX = 0;
+
+struct JSONWarningSourceData {
+    JSONWarningSourceData() = default;
+    static JSONWarningSourceData constructFrom(const processor::WarningSourceData& warningData) {
```
Comment (acquamarin) [inline extension/json/src/functions/table_functions/json_scan.cpp:30]: Let's keep the struct body simple.
Can you declare `constructFrom` and implement it after the struct body?

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 6 above)
Comment (acquamarin) [reply extension/json/src/functions/table_functions/json_scan.cpp:484]: Yes, the numer of readers should be defined as `std::atomic<uint64_t>`

File: extension/json/test/scan_json.test [hunk 9]
```diff
@@ -104,23 +104,45 @@ Cannot read from JSON Object to FLOAT
...
+---- ok
+-STATEMENT CREATE REL TABLE knows(FROM person TO person)
+---- ok
+-STATEMENT COPY person FROM "${KUZU_ROOT_DIRECTORY}/dataset/json-error/person_ok.json";
+---- ok
+-STATEMENT COPY knows FROM "${KUZU_ROOT_DIRECTORY}/dataset/json-error/index_lookup_error.json"(IGNORE_ERRORS=true);
+---- ok
+-STATEMENT CALL show_warnings() RETURN message, file_path, line_or_record_number, skipped_line_or_record
+---- 2
+Unable to find primary key value 5.|${KUZU_ROOT_DIRECTORY}/dataset/json-error/index_lookup_error.json|3|{"from": 1, "to": 5}
```
Comment (acquamarin) [inline extension/json/test/scan_json.test:137]: I am little bit confused about the term `record` in json. Should we simply show the line number in the original json file? let's discuss this.

File: src/processor/warning_context.cpp [hunk 10]
```diff
@@ -1,36 +1,34 @@
...
-    : message(std::move(message)), completedLine(completedLine),
-      warningData(std::move(warningData)), mustThrow(mustThrow) {}
-
-bool CSVError::operator<(const CSVError& o) const {
-    if (warningData.blockIdx == o.warningData.blockIdx) {
-        return warningData.rowOffsetInBlock < o.warningData.rowOffsetInBlock;
-    }
-    return warningData.blockIdx < o.warningData.blockIdx;
+
+namespace {
```
[the remark this answers is not in the document]
Comment (royi-luo) [reply src/processor/warning_context.cpp:11]: It's an anonymous namespace, the main purpose is to give anything inside internal linkage (so in this case it should be the same as adding `static` in front of the contained function declarations).

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 6 above)
Comment (royi-luo) [reply extension/json/src/functions/table_functions/json_scan.cpp:487]: updated

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 8 above)
Comment (royi-luo) [reply extension/json/src/functions/table_functions/json_scan.cpp]: updated

File: src/include/common/utils.h (hunk 2 above)
Comment (royi-luo) [reply src/include/common/utils.h]: updated

File: extension/json/src/functions/table_functions/json_scan.cpp [hunk 11]
```diff
@@ -236,31 +332,73 @@ static uint8_t* nextJson(uint8_t* ptr, uint64_t size) {
...
             }
             break;
         }
     }
-    return ptr == end ? nullptr : ptr;
+
+    if (ptr == end) {
+        return nullptr;
+    }
+    return ptr;
```
Comment (royi-luo) [inline extension/json/src/functions/table_functions/json_scan.cpp:348]: revert

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 5 above)
Comment (royi-luo) [reply extension/json/src/functions/table_functions/json_scan.cpp:381]: That PR ended up not fixing everything 😭 so I ended fixing the rest here.

File: extension/json/src/functions/table_functions/json_scan.cpp [hunk 12]
```diff
@@ -21,6 +23,27 @@ using namespace kuzu::common;
 
 struct JsonScanBindData;
 
+static constexpr idx_t JSON_SCAN_FILE_IDX = 0;
```
Comment (acquamarin) [inline extension/json/src/functions/table_functions/json_scan.cpp:26]: I would move this filed under JSON_EXTENSION class.

File: extension/json/src/functions/table_functions/json_scan.cpp [hunk 13]
```diff
@@ -97,25 +142,63 @@ struct JSONScanLocalState : public TableFuncLocalState {
...
+        main::ClientContext* context)
+        : docs{}, currentReader{sharedState.jsonReader.get()},
           reconstructBuffer{
               mm.allocateBuffer(false /* initializeToZero */, JsonConstant::SCAN_BUFFER_CAPACITY)},
-          mm{mm} {}
+          mm{mm}, lineCountInBuffer(0),
+          errorHandler(std::make_unique<processor::LocalFileErrorHandler>(
+              &sharedState.sharedErrorHandler, false, context)) {}
+
+    ~JSONScanLocalState() override {
```
Comment (acquamarin) [inline extension/json/src/functions/table_functions/json_scan.cpp:160]: I would suggest moving the definition after the class declaration

File: test/test_files/exceptions/copy/null_pk.test [hunk 14]
```diff
@@ -21,7 +21,7 @@ Copy exception: Found NULL, which violates the non-null constraint of the primar
 ---- 2
 alice
 bob
--STATEMENT CALL show_warnings() RETURN query_id, message, file_path, skipped_line, line_number
+-STATEMENT CALL show_warnings() RETURN query_id, message, file_path, skipped_line_or_record, line_number
```
Comment (acquamarin) [inline test/test_files/exceptions/copy/null_pk.test:24]: Should we still keep using the original term `skipped_line`?

File: src/processor/warning_context.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (acquamarin) [reply src/processor/warning_context.cpp:11]: i think it is better to use static keyword instead of a new namespace.
@ray6080 can comment on this.

**Review by acquamarin — APPROVED** [review]
Good work! Looks good to me.

File: test/test_files/exceptions/copy/null_pk.test (hunk 14 above)
Comment (royi-luo) [reply test/test_files/exceptions/copy/null_pk.test:24]: The thing is that it is possible for it not to be a line (it can be part of or multiple lines) so I feel like `skipped_line` is a bit misleading

File: extension/json/test/scan_json.test (hunk 9 above)
Comment (royi-luo) [reply extension/json/test/scan_json.test:137]: Discussed offline, we will show line number + skipped line/record

File: src/processor/warning_context.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (royi-luo) [reply src/processor/warning_context.cpp:11]: I'll change it regardless since I don't feel too strongly about either option in this case

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 12 above)
Comment (royi-luo) [reply extension/json/src/functions/table_functions/json_scan.cpp]: updated

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 13 above)
Comment (royi-luo) [reply extension/json/src/functions/table_functions/json_scan.cpp]: updated

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 5 above)
Comment (ray6080) [reply extension/json/src/functions/table_functions/json_scan.cpp:379]: Can u open an issue on running extension tests with asan?

**Review by ray6080 — APPROVED** [review]

File: extension/json/src/functions/table_functions/json_scan.cpp (hunk 5 above)
Comment (royi-luo) [reply extension/json/src/functions/table_functions/json_scan.cpp:379]: opened https://github.com/kuzudb/kuzu/issues/4312

File: src/include/common/data_chunk/data_chunk.h (hunk 1 above)
Comment (royi-luo) [reply src/include/common/data_chunk/data_chunk.h:36]: I'll do this in a separate PR since this will involve some more heavy refactoring https://github.com/kuzudb/kuzu/issues/4313
