### PR TITLE
Fix string function bugs

### LINKED ISSUE #3890: Bug: Wrong result on "suffix" function with repetitive string
### Kùzu version

v0.4.2

### What operating system are you using?

Ubuntu 22.04

### What happened?

Hi! I have discovered a bug in Kuzu when dealing with suffix function. It seems to give wrong results on strings with repetitive letters. For example, consider:
```cypher
RETURN suffix("bbbb", "bb"); 
```
Apparently, this is true. However, Kuzu gives a false result:
image
To be honest, in the first place, I was not sure whether this mistake was due to the wrong parameter order, so I also tried the other way around (RETURN suffix("bb", "bbbb")), and it still gave false 🤣
Thank you!

### Are there known steps to reproduce?

No other steps. Just run the query.

### LINKED ISSUE #3892: Bug: Heap use after free on substring function with negative starting index
### Kùzu version

v0.4.2

### What operating system are you using?

Ubuntu 22.04

### What happened?

Hi! I discovered a vulnerability where the substring function with a negative starting index could cause the heap-use-after-free vulnerability. This could have security implications.
For example, consider the following query:
```cypher
return substring('abbbb', -9999, 2);
``` 
The return result becomes abnormal with different negative starting index:
image
After instrumenting with address sanitizer, it's easier to discover the root cause, as the read operation in `kuzu::common::ku_string_t::setLongString(char const*, unsigned long) kuzu/kuzu/src/include/common/types/ku_string.h:49` is previously freed by `PredictionModeClass::hasSLLConflictTerminatingPrediction(antlr4::atn::PredictionMode, antlr4::atn::ATNConfigSet*)kuzu/kuzu/third_party/antlr4_runtime/src/atn/PredictionMode.cpp:61`. To facilitate analysis, I have attached detailed log in the pastebin: https://pastebin.mozilla.org/dT7QgRjE

Thank you!

### Are there known steps to reproduce?

_No response_

### LINKED ISSUE #3909: Bug: End with may produce wrong result on ALL strings with just one additional length
### Kùzu version

v0.4.2

### What operating system are you using?

Ubuntu 22.04

### What happened?

Hi! I have discovered that Kuzu may produce wrong results on all `ends with` as long as the second string is one letter longer than the first parameter. For example:
```cypher
return '1' ends with '23';
```
Obviously, this should be 'False'. However, Kuzu returns 'True':
image
Thank you!

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by mxwli**
# Description

Fixes #3892,
Fixes #3890,
Fixes #3909

Note:
the following definition for `ku_string_t` seems unsafe.
```cpp
    uint32_t len;
    uint8_t prefix[PREFIX_LENGTH];
    union {
        uint8_t data[INLINED_SUFFIX_LENGTH];
        uint64_t overflowPtr;
    };
```

If `len < PREFIX_LENGTH + INLINED_SUFFIX_LENGTH`, then we write data to `prefix`, which is only size `PREFIX_LENGTH`. This seems to have been made under the assumption that the union data will be packed right after prefix, which works for the compilers we use, but isn't guaranteed to work in the general case.

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/include/function/string/functions/ends_with_function.h [hunk 1]
```diff
@@ -1,17 +1,27 @@
...
 namespace kuzu {
 namespace function {
 
 struct EndsWith {
     static inline void operation(common::ku_string_t& left, common::ku_string_t& right,
         uint8_t& result) {
-        int64_t pos = 0;
-        Find::operation(left, right, pos);
-        result = (pos == left.len - right.len + 1);
+        if (right.len > left.len) {
```
Comment (acquamarin) [inline src/include/function/string/functions/ends_with_function.h:11]: Why can't we reuse the find function? 
If there is a bug in the find function we should fix that
And this new code doesn't handle utf-8 correctly.

File: src/include/function/string/functions/substr_function.h [hunk 2]
```diff
@@ -17,7 +17,7 @@ struct SubStr {
         bool isAscii = true;
         int64_t startPos = start - 1;
         int64_t endPos = std::min(srcStr.size(), (size_t)(startPos + len));
-        if (startPos >= endPos) {
+        if (startPos >= endPos || src.isOutOfBounds(startPos) || src.isOutOfBounds(endPos - 1)) {
```
Comment (acquamarin) [inline src/include/function/string/functions/substr_function.h:20]: I would not add a new function isOutOfBound
I don't think endpos can be out of bound since the value is calculated by: std::min(srcStr.size(), (size_t)(startPos + len));

File: src/include/function/string/functions/ends_with_function.h (hunk 1 above)
Comment (mxwli) [reply src/include/function/string/functions/ends_with_function.h:11]: Find is logically incorrect; find("bbbb", "b") gives index 1. We then conclude that "b" is not a suffix of "bbbb"

File: src/include/function/string/functions/substr_function.h (hunk 2 above)
Comment (mxwli) [reply src/include/function/string/functions/substr_function.h:20]: That's true. I'll just check startPos without a function.

**Review by acquamarin — APPROVED** [review]
