### PR TITLE
Fix list_to_string with blob bug

### LINKED ISSUE #5745: list_to_string: cannot operate on BLOB lists
```cypher
kuzu> RETURN list_to_STRING('-',[BLOB('\\xBC\\xBD\\xBA\\xAA')]);
Error: Assertion failed in file "<>/src/common/type_utils.cpp" on line 94: KU_UNREACHABLE

kuzu> RETURN list_to_STRING('-', cast(['long string 1', 'long string 2'], 'BLOB[]'));
Error: Assertion failed in file "<>/src/common/type_utils.cpp" on line 94: KU_UNREACHABLE

kuzu> RETURN list_to_STRING('-', cast(['long string 1', 'long string 2'], 'STRING[]'));
┌──────────────────────────────────────────────────────────────┐
│ LIST_TO_STRING(-,LIST_CREATION(long string 1,long string 2)) │
│ STRING                                                       │
├──────────────────────────────────────────────────────────────┤
│ long string 1-long string 2                                  │
└──────────────────────────────────────────────────────────────┘

```

### PR DESCRIPTION
**Pull request by acquamarin**
Handle BLOB type correctly in list_to_string function
Closes #5745

### CODE REVIEW

File: src/common/type_utils.cpp [hunk 1]
```diff
@@ -70,6 +70,8 @@ std::string TypeUtils::entryToString(const LogicalType& dataType, const uint8_t*
         return TypeUtils::toString(*reinterpret_cast<const timestamp_t*>(value));
     case LogicalTypeID::INTERVAL:
         return TypeUtils::toString(*reinterpret_cast<const interval_t*>(value));
+    case LogicalTypeID::BLOB:
```
Comment (sdht0) [inline src/common/type_utils.cpp:73]: I also see `RECURSIVE_REL` `ANY` and `POINTER` not covered here.
Should `RECURSIVE_REL` be also added here?

**Review by sdht0 — APPROVED** [review]
Thanks

**Review by andyfengHKU — APPROVED** [review]
let's throw exception inside of KU_UNREACHABLE to be safer
