### PR TITLE
Fix date-part function

### LINKED ISSUE #4667: Bug: date_part function giving incorrect results
### Kùzu version

latest

### What operating system are you using?

_No response_

### What happened?

```
kuzu> MATCH (p:persons) WHERE date_part('year', p.birth_date) >= 1915 AND date_part('year', p.birth_date) < 1970 RETURN count(p);
┌──────────────┐
│ COUNT(p._ID) │
│ INT64        │
├──────────────┤
│ 0            │
└──────────────┘
(1 tuple)
(1 column)
Time: 0.20ms (compiling), 16.66ms (executing)
kuzu> MATCH (p:persons) RETURN date_part('year', p.birth_date) LIMIT 10;
┌──────────────────────────────┐
│ DATE_PART(year,p.birth_date) │
│ INT64                        │
├──────────────────────────────┤
│ 1903                         │
│ 1931                         │
│ 1927                         │
│ 1975                         │
│ 1927                         │
│ 1981                         │
│ 1946                         │
│ 1942                         │
│ 1973                         │
│ 1950                         │
└──────────────────────────────┘
(10 tuples)
(1 column)
Time: 0.13ms (compiling), 0.55ms (executing)
```

In the first query, filter returns 0 as count whereas as you see in the second query there are years which are less than 1970 and greater than 1915.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by acquamarin**
Fixes date-part function bug which is caused by a reference passing.
Closes #4667

### CODE REVIEW

File: src/common/types/date_t.cpp [hunk 1]
```diff
@@ -413,7 +413,7 @@ date_t Date::getLastDay(date_t& date) {
     return Date::fromDate(year, month, 1) - 1;
 }
 
-int32_t Date::getDatePart(DatePartSpecifier specifier, date_t& date) {
+int32_t Date::getDatePart(DatePartSpecifier specifier, date_t date) {
```
Comment (ray6080) [inline src/common/types/date_t.cpp:416]: What about its caller `Date::trunc`? Should that take in a reference of `date_t` after this change?

Can you double check if we have the same problem in other functions? I found we use references a lot in date related functions. I would carefully go through each of them to do some due intelligence checks.

Also, if we have to use reference to avoid copying overheads, I would suggest we should add `const` qualifier to make sure the input is safe without any changes.
