### PR TITLE
cli: create history file in home directory

### LINKED ISSUE #5771: Move the CLI history file to Kuzu home directory by default and cap its size to a reasonable number
### Kuzu version

v0.11.0

### What operating system are you using?

Ubuntu 24.04

### What happened?

```
mkdir tmp && cd tmp
kuzu foo
kuzu> create node table node(id int primary key);
...
➜  ls
foo  foo.lock  history.txt
```

Prefer to see only `foo`. But see two extra files.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by sdht0**
There is a default limit of 1000 lines, which is not configurable as of now.

Fixes #5771
Associated docs (issue or PR): TODO

### CODE REVIEW

File: tools/shell/shell_runner.cpp [hunk 1]
```diff
@@ -123,17 +123,30 @@ int main(int argc, char* argv[]) {
...
 
+    const std::string historyFile = "history.txt";
     auto pathToHistory = args::get(historyPathFlag);
     if (!pathToHistory.empty() && pathToHistory.back() != '/') {
         pathToHistory += '/';
     }
-    pathToHistory += "history.txt";
+    // If `historyFile` is present in the current directory, use that to preserve backward
+    // compatibility.
+    if (pathToHistory.empty() && !std::filesystem::exists(historyFile)) {
```
Comment (ray6080) [inline tools/shell/shell_runner.cpp:133]: Need to double check, but I assume we must have similar piece of code somewhere else that's creating the kuzu home directory?

Comment (sdht0) [reply tools/shell/shell_runner.cpp:133]: Yes in `ExtensionInstaller::installExtension` using `ClientContext.homeDirectory`.

Comment (sdht0) [reply tools/shell/shell_runner.cpp:133]: Moved the getUserHomeDir logic to ClientContext. The extensions code creates something like `~/.kuzu/<extension>/...` which is independent from the history logic.

**Review by mewim — APPROVED** [review]
CI and Makefile LGTM
