### PR TITLE
query profiler: segfault trying to profile export database

### LINKED ISSUE #5802: query profiler: segfault when trying to profile export database
### Kuzu version

0.11.0

### What operating system are you using?

MacOS

### What happened?

Found while working on https://github.com/kuzudb/kuzu/issues/5727

```
kuzu> profile export database "tmp";
zsh: segmentation fault  ./build/debug/tools/shell/kuzu
tanvirgahunia@Tanvirs-MacBook-Pro kuzu %
```

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by tgahunia05**
# Description

There is no nullptr check on the function `copyChildSchema` which is called by `LogicalExplain::computeSchema`.
The segfault in the issue was caused by a nullptr dereference on the `schema` member. This PR creates an empty schema if the child schema is nullptr. This may not be the right fix; we may want to check how this was ever nullptr. Pinging @andyfengHKU to validate. 

Fixes #5802 

- [X] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/include/planner/operator/logical_operator.h [hunk 1]
```diff
@@ -135,7 +135,14 @@ class KUZU_API LogicalOperator {
 
 protected:
     void createEmptySchema() { schema = std::make_unique<Schema>(); }
-    void copyChildSchema(uint32_t idx) { schema = children[idx]->getSchema()->copy(); }
+    void copyChildSchema(uint32_t idx) {
```
Comment (andyfengHKU) [inline src/include/planner/operator/logical_operator.h:138]: Let's limit the change to `LogicalExplain` only and keep LogicalOperator as it is

**Review by andyfengHKU — APPROVED** [review]
