### PR TITLE
Fix nested aggregate

### LINKED ISSUE #2736: BI benchmark query template 5: Nested Aggregation Bug
Results of aggregations being put into aggregations give `Binder exception: Excpression contains nested aggregation`. Eg:
```
CREATE NODE TABLE t1(id SERIAL, PRIMARY KEY(id));
MATCH(t:t1) WITH count(t.id) AS cnt WITH sum(cnt) AS scnt RETURN scnt;
```

This bug was initially found in LDBC SNB BI Query 5:
```
MATCH (tag:Tag {name: $tag})<-[:HAS_TAG]-(message:Post:Comment)-[:HAS_CREATOR]->(person:Person)
OPTIONAL MATCH (message)<-[likes:LIKES]-(:Person)
WITH person, message, count(likes) AS likeCount
OPTIONAL MATCH (message)<-[:REPLY_OF]-(reply:Comment)
WITH person, message, likeCount, count(reply) AS replyCount
WITH person, count(message) AS messageCount, sum(likeCount) AS likeCount, sum(replyCount) AS replyCount
RETURN
  person.id,
  replyCount,
  likeCount,
  messageCount,
  1*messageCount + 2*replyCount + 10*likeCount AS score
ORDER BY
  score DESC,
  person.id ASC
LIMIT 100
```

Where sum(likeCount) gives the error.

### PR DESCRIPTION
**Pull request by andyfengHKU**
# Description

Please include a summary of the changes and the related issue (if applicable). Please also include
relevant motivation and context.

Fixes #2736 

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/binder/expression_binder.cpp [hunk 1]
```diff
@@ -20,7 +20,7 @@ using namespace kuzu::parser;
 namespace kuzu {
 namespace binder {
 
-static void validateAggregationExpressionIsNotNested(std::shared_ptr<Expression> expression);
+// static void validateAggregationExpressionIsNotNested(std::shared_ptr<Expression> expression);
```
Comment (ray6080) [inline src/binder/expression_binder.cpp:23]: Remove this line.

File: src/binder/bind/bind_projection_clause.cpp [hunk 2]
```diff
@@ -131,6 +131,27 @@ std::pair<expression_vector, std::vector<std::string>> Binder::bindProjectionLis
...
+    for (auto& agg : aggs) {
+        if (scope.contains(agg->getAlias())) {
+            continue;
+        }
+        numAggs++;
+    }
+    if (numAggs > 0) {
+        throw BinderException(
+            stringFormat("Expression {} contains nested aggregation.", expr.toString()));
+    }
```
Comment (ray6080) [inline src/binder/bind/bind_projection_clause.cpp:152]:
```suggestion
    for (auto& agg : aggs) {
        if (!scope.contains(agg->getAlias())) {
            throw BinderException(
                stringFormat("Expression {} contains nested aggregation.", expr.toString()));
        }
    }
```

Seems L142- L152 can be simplified.

**Review by ray6080 — APPROVED** [review]
