### PR TITLE
Fix return same column with different alias

### LINKED ISSUE #3913: Bug: `LOAD FROM` does not allow retrurning the same column twice
### Kùzu version

v0.4.2

### What operating system are you using?

_No response_

### What happened?

`LOAD FROM "demo-csv/city.csv" RETURN column0, column0;` is throwing the error `Error: Binder exception: Multiple result column with the same name column0 are not supported.` as expected.

However, it should be possible to return the column twice by renaming: `LOAD FROM "demo-csv/city.csv" RETURN column0 AS C0, column0 AS C1;`. This query fails with a similar error: `Error: Binder exception: Multiple result column with the same name C1 are not supported.`.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by andyfengHKU**
# Description

When we return the same column with different aliases, current master treat these columns with the same column name and triggers an exception. This PR fixes this by passing `columnNames` to `StatementResult`.

An alternative solution is to copy column expression so that each column expression is of its own object and thus can have its own alias/column name. Both solution make sense to me so I picked the one with less work.

Fixes #3913

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/binder/bind/bind_projection_clause.cpp [hunk 1]
```diff
@@ -74,10 +74,55 @@ static std::pair<expression_vector, std::vector<std::string>> rewriteProjectionI
...
+        }
+    }
+    auto columnNames = getColumnNames(projectionExprs, aliases);
+    validateColumnNamesAreUnique(columnNames);
+    // Rewrite projection list
+    auto originalProjectionExprs = projectionExprs;
+    auto originalAliases = aliases;
+    auto [a, b] = rewriteProjectionInWithClause(projectionExprs, aliases);
+    projectionExprs = a;
+    aliases = b;
```
Comment (ray6080) [inline src/binder/bind/bind_projection_clause.cpp:117]: Why not just use new variable names `rewrittenProjectionExprs`, and `rewriteenAliases`?

**Review by ray6080 — APPROVED** [review]
