### PR TITLE
Fix json casting issue

### LINKED ISSUE #4986: Bug: Inconsistent behaviour of `to_json` function
### Kùzu version

v0.8.2

### What operating system are you using?

MacOS Sequoia 15.3.1

### What happened?

First off, I'm loving kuzu -- great job everyone!

I'm attempting to write a query returning nodes for which a particular JSON property matches a user-provided query in the form of a path and expected value. In python:

```python
conn.execute(
    """\
    MATCH (n)
    WHERE json_extract(n.property, $p) = $v
    RETURN n
    """,
    parameters={
        "p": "path/into/json",
        "v": "value",
    },
)
```
This results in an exception:
```
RuntimeError: Binder exception: Data type of expression json_extract(n.property,$p) should not be modified.
```

This seems a little odd, but not the end of the world. Modifying the query slightly, wrapping the right-hand side of the comparison in `to_json` allows the query to run, but this is where I start seeing strange behaviour -- certain values yield strange results. Rather than worry about creating and populating a table to test, It's easier to illustrate with a simpler example:

```cypher
RETURN json_extract(json_object("foo", XXX), "foo") = to_json(XXX);
```
Aside from `NULL`, I'd expect the above to return `true` for any valid JSON, but it doesn't.

## Works as expected

✅ String value (`"bar"`)
```
kuzu> RETURN json_extract(json_object("foo", "bar"), "foo") = to_json("bar");
┌─────────────────────────────────────────────────────────────┐
│ EQUALS(json_extract(json_object(foo,bar),foo),to_json(bar)) │
│ BOOL                                                        │
├─────────────────────────────────────────────────────────────┤
│ True                                                        │
└─────────────────────────────────────────────────────────────┘
```

✅ Integer value (`5`)
```
kuzu> RETURN json_extract(json_object("foo", 5), "foo") = to_json(5);
┌─────────────────────────────────────────────────────────┐
│ EQUALS(json_extract(json_object(foo,5),foo),to_json(5)) │
│ BOOL                                                    │
├─────────────────────────────────────────────────────────┤
│ True                                                    │
└─────────────────────────────────────────────────────────┘
```

✅ Boolean value (`true`)
```
kuzu> RETURN json_extract(json_object("foo", true), "foo") = to_json(true);
┌───────────────────────────────────────────────────────────────┐
│ EQUALS(json_extract(json_object(foo,True),foo),to_json(True)) │
│ BOOL                                                          │
├───────────────────────────────────────────────────────────────┤
│ True                                                          │
└───────────────────────────────────────────────────────────────┘
```

## Unexpected results

❌ String containing integer (`"5"`)
```
kuzu> RETURN json_extract(json_object("foo", "5"), "foo") = to_json("5");
┌─────────────────────────────────────────────────────────┐
│ EQUALS(json_extract(json_object(foo,5),foo),to_json(5)) │
│ BOOL                                                    │
├─────────────────────────────────────────────────────────┤
│ False                                                   │
└─────────────────────────────────────────────────────────┘
```

❌ String containing boolean (`"true"`)
```
kuzu> RETURN json_extract(json_object("foo", "true"), "foo") = to_json("true");
┌───────────────────────────────────────────────────────────────┐
│ EQUALS(json_extract(json_object(foo,true),foo),to_json(true)) │
│ BOOL                                                          │
├───────────────────────────────────────────────────────────────┤
│ False                                                         │
└───────────────────────────────────────────────────────────────┘
```

The left-hand side (`json_extract`) is always returning what I'd expect -- a JSON-encoded string. The right-hand side (`to_json`) appears to sometimes interpret its input as a literal and sometimes interpret as a JSON document. Since, in my use case, both the path and value are provided by the user, I appear to have no choice but to make use of `to_json` (else hit a binder exception) but that has gives unexpected results.

### Are there known steps to reproduce?

Prerequisite:
```
INSTALL JSON;
LOAD EXTENSION JSON;
```

Minimal examples highlighting inconsistent behaviour of `to_json`:
```
kuzu> RETURN to_json(5);
┌────────────┐
│ to_json(5) │
│ json       │
├────────────┤
│ 5          │
└────────────┘
kuzu> RETURN to_json("5");
┌────────────┐
│ to_json(5) │
│ json       │
├────────────┤
│ 5          │
└────────────┘
kuzu> RETURN to_json(true);
┌───────────────┐
│ to_json(True) │
│ json          │
├───────────────┤
│ true          │
└───────────────┘
kuzu> RETURN to_json("true");
┌───────────────┐
│ to_json(true) │
│ json          │
├───────────────┤
│ true          │
└───────────────┘

### PR DESCRIPTION
**Pull request by acquamarin**
Fixes #4986
Delete the minimal type inference from the jsonify function which is only used in casting before.
The PR introduces a new execFunc for casting string->json which only needs parsing to check errors in json.

### CODE REVIEW

File: extension/json/src/functions/cast_functions/json_cast.cpp [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+        }
+        yyjson_doc_free(doc);
+        StringVector::addString(&result, resultPos, str);
+    }
+}
+
+static std::unique_ptr<FunctionBindData> bindFunc(ScalarBindFuncInput input) {
+    LogicalType type = input.arguments[0]->getDataType().copy();
+    if (type.getLogicalTypeID() == LogicalTypeID::ANY) {
+        type = LogicalType::INT64();
```
Comment (andyfengHKU) [inline extension/json/src/functions/cast_functions/json_cast.cpp:39]: When will this be triggered? I would have a test case on this.

Comment (acquamarin) [reply extension/json/src/functions/cast_functions/json_cast.cpp:39]: We already have a test for it. e.g. `cast(null as json)`
