### PR TITLE
neo4j: fix properties parsing, allow all types

### LINKED ISSUE #5351: neo4j: handle more data types, graceful error handling
- [ ] time()
- [ ] duration()
- [ ] localdatetime()
- [ ] localtime()
- [ ] datetime('2023-05-01T10:15:30+01:00'): fails to parse
- [ ] point()

Ref: https://neo4j.com/docs/cypher-manual/current/values-and-types/property-structural-constructed/

Currently, the extension simply stops the import with an error.

- [ ] If we don't want to support any of the types, the extension should handle the type gracefully by either skipping the type or converting it to a string.
- [ ] `Error: Binder exception: Number of columns mismatch. Expected 6 but got 8.` after multiple deletes and creates. Help debug these weird cases by better logging.

Test data:
```cypher
CREATE
  (a:Person {
    id: 1,
    name: 'Alice',
    age: 30,
    verified: true,
    score: 88.5,
    tags: ['tag1', 'tag2'],
    joinedDate: date('2023-05-01'),
    sessionTime: duration('PT2H30M'),
    createdAt: localdatetime('2023-05-01T10:15:30'),
    loginTime: localtime('10:15:30'),
    location: point({latitude: 52.52, longitude: 13.405}),
    timezone: time('10:15:30+01:00'),
    createdZoned: datetime('2023-05-01T10:15:30+01:00')
  }),
  (b:Person {
    id: 2,
    name: 'Bob',
    age: 25,
    verified: false,
    score: 76.2,
    tags: ['tag3', 'tag4'],
    joinedDate: date('2022-11-15'),
    sessionTime: duration('PT1H15M'),
    createdAt: localdatetime('2022-11-15T09:00:00'),
    loginTime: localtime('09:00:00'),
    location: point({latitude: 48.8566, longitude: 2.3522}),
    timezone: time('09:00:00+02:00'),
    createdZoned: datetime('2022-11-15T09:00:00+02:00')
  }),
  (c:Person {
    id: 3,
    name: 'Charlie',
    age: null,
    verified: true,
    score: 67.0,
    tags: ['tag5'],
    joinedDate: date('2021-08-20'),
    sessionTime: duration('PT45M'),
    createdAt: localdatetime('2021-08-20T14:00:00'),
    loginTime: null,
    location: point({latitude: 40.7128, longitude: -74.0060}),
    timezone: time('14:00:00+03:00'),
    createdZoned: datetime('2021-08-20T14:00:00+03:00')
  }),
  (d:Person {
    id: 4,
    name: 'Diana',
    age: 40,
    verified: null,
    score: null,
    tags: null,
    joinedDate: date('2020-03-10'),
    sessionTime: duration('PT1H'),
    createdAt: null,
    loginTime: localtime('11:45:00'),
    location: null,
    timezone: time('11:45:00+00:00'),
    createdZoned: datetime('2020-03-10T11:45:00+00:00')
  }),
  (e:Person {
    id: 5,
    name: 'Evan',
    age: 29,
    verified: true,
    score: 92.1,
    tags: [],
    joinedDate: null,
    sessionTime: null,
    createdAt: null,
    loginTime: null,
    location: null,
    timezone: null,
    createdZoned: null
  }),

  (a)-[:FRIENDS {
    since: date('2020-01-01'),
    strength: 0.85,
    active: true,
    notes: 'Met at event',
    duration: duration('P1Y2M'),
    lastContact: datetime('2024-01-01T12:00:00+01:00')
  }]->(b),

  (b)-[:COLLEAGUES {
    since: date('2021-06-15'),
    strength: 0.75,
    active: false,
    notes: 'Worked together',
    duration: duration('P6M'),
    lastContact: datetime('2023-12-01T09:30:00+02:00')
  }]->(a),

  (a)-[:KNOWS {
    since: null,
    strength: null,
    active: true,
    notes: null,
    duration: null,
    lastContact: null
  }]->(c),

  (c)-[:KNOWS {
    since: date('2019-07-20'),
    strength: 0.6,
    active: null,
    notes: null,
    duration: duration('P3M'),
    lastContact: datetime('2019-10-20T08:00:00+01:00')
  }]->(d),

  (d)-[:FRIENDS {
    since: date('2022-02-02'),
    strength: null,
    active: true,
    notes: '',
    duration: null,
    lastContact: null
  }]->(e);
```

### LINKED ISSUE #5352: neo4j: columns mismatch error
```cypher
kuzu> CALL NEO4J_MIGRATE("localhost", "neo4j", "neo44444", ["Person"], ["KNOWS","FRIENDS"]);
Error: Binder exception: Number of columns mismatch. Expected 6 but got 8.
```
Data inserted into a fresh Neo4j db:
```cypher
CREATE
  (a:Person {
    id: 1,
    name: 'Alice',
    age: 30,
    verified: true,
    score: 88.5,
    tags: ['tag1', 'tag2'],
    joinedDate: date('2023-05-01')
  }),
  (b:Person {
    id: 2,
    name: 'Bob',
    age: 25,
    verified: false,
    score: 76.2,
    tags: ['tag3', 'tag4'],
    joinedDate: date('2022-11-15')
  }),
  (c:Person {
    id: 3,
    name: 'Charlie',
    age: null,
    verified: true,
    score: 67.0,
    tags: ['tag5'],
    joinedDate: date('2021-08-20')
  }),
  (d:Person {
    id: 4,
    name: 'Diana',
    age: 40,
    verified: null,
    score: null,
    tags: null,
    joinedDate: date('2020-03-10')
  }),
  (e:Person {
    id: 5,
    name: 'Evan',
    age: 29,
    verified: true,
    score: 92.1,
    tags: [],
    joinedDate: null
  }),

  (a)-[:FRIENDS {
    since: date('2020-01-01'),
    strength: 0.85,
    active: true,
    notes: 'Met at event'
  }]->(b),

  (b)-[:COLLEAGUES {
    since: date('2021-06-15'),
    strength: 0.75,
    active: false,
    notes: 'Worked together'
  }]->(a),

  (a)-[:KNOWS {
    since: null,
    strength: null,
    active: true,
    notes: null
  }]->(c),

  (c)-[:KNOWS {
    since: date('2019-07-20'),
    strength: 0.6,
    active: null,
    notes: null
  }]->(d),

  (d)-[:FRIENDS {
    since: date('2022-02-02'),
    strength: null,
    active: true,
    notes: ''
  }]->(e);

```

### PR DESCRIPTION
**Pull request by sdht0**
- Fixes https://github.com/kuzudb/kuzu/issues/5352
- Instead of throwing an unknown type error, which I expect a lot of users to encounter pretty soon, let's accept all unknown types as string? Tested and works for all types in https://github.com/kuzudb/kuzu/issues/5351. Optional for this release and will revert if needed.
- 1000 seconds is quite a long timeout for the network connection. Setting it to 30s instead, for much quicker feedback to the users in case of any network error. 

Found a bug in the apoc exporter where timestamps are not exported properly in ISO format. Times like `09:00:00` will be truncated to `09:00`. This will cause the Kuzu parser to fail. Expecting this to be a common issue users with timestamps will face.

# Contributor agreement

- [ ] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).
Closes #5352
Closes #5351

### CODE REVIEW

File: extension/neo4j/src/function/neo4j_migrate.cpp [hunk 1]
```diff
@@ -128,8 +129,8 @@ static std::unique_ptr<TableFuncBindData> bindFunc(ClientContext* /*context*/,
     auto password = input->getLiteralVal<std::string>(2);
     auto cli = std::make_shared<httplib::Client>(url, 7474);
     cli->set_basic_auth(userName, password);
-    cli->set_connection_timeout(std::chrono::seconds(1000));
-    cli->set_read_timeout(std::chrono::seconds(1000));
+    cli->set_connection_timeout(std::chrono::seconds(30));
```
Comment (acquamarin) [inline extension/neo4j/src/function/neo4j_migrate.cpp]: We should give enough time for neo4j apoc extension to export all the nodes and rels.
For example, it is possible that neo4j takes 2mins to export a node to csv.

**Review by acquamarin — APPROVED** [review]

**Review by acquamarin — COMMENTED** [review]
Thanks for fixing! @sdht0

File: extension/neo4j/src/function/neo4j_migrate.cpp (hunk 1 above)
Comment (sdht0) [reply extension/neo4j/src/function/neo4j_migrate.cpp]: Okay, how about just `set_connection_timeout` to be 30s then?

I did face this issue once where the CLI got stuck for a long time, as mentioned in https://github.com/kuzudb/kuzu/issues/5341.
