### PR TITLE
Fix label predicate in recursive pattern

### LINKED ISSUE #4918: Bug: Clarify `r, n` in recursive relation filter `(r,n | WHERE ...)`
### Kùzu version

nightly

### What operating system are you using?

_No response_

### What happened?

Consider following graph:
```cypher
CREATE NODE TABLE V (id int PRIMARY KEY);
CREATE REL TABLE E (FROM V TO V, val STRING);
CREATE (:V {id: 1})-[:E {val: "foo"}]->(:V {id: 2});
```
and a recursive query with predicate:
```cypher
MATCH (a)-[:E * (r,n | WHERE n.id = 1)]->(b) RETURN *;
```
I'd assume `r` is set to `:E` relation above, and `n` is NOOP/unset variable, as there is just 1 intermediate hop. Endpoint nodes are covered by `a` and `b` variables and no `n` node in-between exists with current data.

At least below queries reflect this assumption (it doesn't matter what value `x` is typed for `WHERE n.id = x`):
```cypher
kuzu> MATCH (a)-[:E * (r,n | WHERE n.id = 1)]->(b) RETURN *;
┌──────────────────────────────┬──────────────────────────────┐
│ a                            │ b                            │
│ NODE                         │ NODE                         │
├──────────────────────────────┼──────────────────────────────┤
│ {_ID: 0:0, _LABEL: V, id: 1} │ {_ID: 0:1, _LABEL: V, id: 2} │                                                                                                                                
└──────────────────────────────┴──────────────────────────────┘                                                                                                                                
                                                                                                                                                                                               
kuzu> MATCH (a)-[:E * (r,n | WHERE n.id = 100000)]->(b) RETURN *;                                                                                                                              
┌──────────────────────────────┬──────────────────────────────┐                                                                                                                                
│ a                            │ b                            │                                                                                                                                
│ NODE                         │ NODE                         │                                                                                                                                
├──────────────────────────────┼──────────────────────────────┤                                                                                                                                
│ {_ID: 0:0, _LABEL: V, id: 1} │ {_ID: 0:1, _LABEL: V, id: 2} │                                                                                                                                
└──────────────────────────────┴──────────────────────────────┘                                                                                                                                
```                                                                                                                                                                                            
                                                                                                                                                                                               
On the other side, `label(n)` is evaluated (to false in last case) and not ignored:                                                                                                            
```cypher                                                                                                                                                                                      
kuzu> MATCH (a)-[:E * (r,n | WHERE label(n) = "V")]->(b) RETURN *;                                                                                                                             
┌──────────────────────────────┬──────────────────────────────┐                                                                                                                                
│ a                            │ b                            │                                                                                                                                
│ NODE                         │ NODE                         │                                                                                                                                
├──────────────────────────────┼──────────────────────────────┤                                                                                                                                
│ {_ID: 0:0, _LABEL: V, id: 1} │ {_ID: 0:1, _LABEL: V, id: 2} │                                                                                                                                
└──────────────────────────────┴──────────────────────────────┘                                                                                                                                
                                                                                                                                                                                               
kuzu> MATCH (a)-[:E * (r,n | WHERE label(n) = "Foo")]->(b) RETURN *;                                                                                                                           
┌──────┬──────┐                                                                                                                                                                                
│ a    │ b    │                                                                                                                                                                                
│ NODE │ NODE │                                                                                                                                                                                
├──────┼──────┤                                                                                                                                                                                
└──────┴──────┘                                                                                                                                                                                
```                                                                                                                                                                                            
Hence I am not sure about current behavior of `r` and `n`: Shouldn't Kuzu raise an error, if `n` in a recursive filter predicate is used, given there are not intermediate nodes and this variable cannot be set to any node? Alternatively every expression involving `n` might be made NOOP.                           

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by andyfengHKU**
# Description

If a node is single labeled, we rewrite its label function as string literal. This however, should be applied to recursive pattern predicate because if path is of length <= 1, there is no intermediate node and thus the predicate should be a noop. If we try to evaluate, it may lead to empty result. e.g.
```
 [* (r, n | WHERE label(n)='dummy') ]
```

Fixes #4918

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

### CODE REVIEW

File: src/binder/bind/bind_graph_pattern.cpp [hunk 1]
```diff
@@ -381,36 +380,39 @@ std::shared_ptr<RelExpression> Binder::createRecursiveQueryRel(const parser::Rel
             predicate);
     }
     // Bind predicates in (r, n | WHERE )
-    std::shared_ptr<Expression> nodePredicate;
     bool emptyRecursivePattern = false;
+    std::shared_ptr<Expression> nodePredicate;
     if (recursivePatternInfo->whereExpression != nullptr) {
+        expressionBinder.config.disableLabelFunctionLiteralRewrite = true;
```
Comment (acquamarin) [inline src/binder/bind/bind_graph_pattern.cpp:386]: Can we make this as a function?
E.g.
```
expressionBinder.disableFunctionLabelRewrite()
```

File: src/function/pattern/label_function.cpp [hunk 2]
```diff
@@ -74,27 +74,32 @@ std::shared_ptr<Expression> LabelFunction::rewriteFunc(const RewriteFunctionBind
         return expressionBinder->bindScalarFunctionExpression(children,
             StructExtractFunctions::name);
     }
+    auto disableLiteralRewrite = expressionBinder->getConfig().disableLabelFunctionLiteralRewrite;
```
Comment (acquamarin) [inline src/function/pattern/label_function.cpp:77]: Can we not expose the ExpressionBinderConfig?
We can expose an api in expressionBinder like: `expressionBinder->allowLabelFunctionRewrite`?

**Review by acquamarin — APPROVED** [review]

File: src/binder/bind/bind_graph_pattern.cpp (hunk 1 above)
Comment (andyfengHKU) [reply src/binder/bind/bind_graph_pattern.cpp:386]: Alright I solve this separately.

File: src/function/pattern/label_function.cpp (hunk 2 above)
Comment (andyfengHKU) [reply src/function/pattern/label_function.cpp:77]: Ditto
